var vt = [];
var vte = [];
export var dbset = [];

var dbbtn = `<div id="dbbutton" class="textshirt dbbutton" style="top: 91.3769%; left: 95.4652%; width: 36px; height: 36px;"><div id="dbbutton2" class="dbbutton textshirt circleshirt" style="height: 36px; width: 36px; top: 91.3769%; left: 95.4652%; background-color: rgb(255, 255, 255); border-color: rgb(255, 255, 255); color: rgb(255, 255, 255);"></div><div id="dbbutton3" class="dbbutton textshirt circleshirt" style="height: 22px; width: 22px; top: 92.4896%; left: 96.0907%;"></div></div>`;

//to adjust
export const dbtitle = 'Chalon';
const defaultspeed = 25;
const transws = ' wspeed_10';
const drabindex = 'chalon';

const bimgpath = storyline.jsonUrl+'./drawboard/bimg/openbook-581128.jpg';
var dbbg =`<div id="dbbackg" class="textshirt imageshirt" style="left: -14px; top: -72px; width: 1280px; height: 853px;"><img src="`+bimgpath+`"></div>`;
dbbg += '<style>.textshirt{color:#000;font-family:EBGaramond;}</style>';

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 46px; left: 405px; font-size: 26px;">Chalon</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 101px; left: 406px; height: 360px;">he woke up wanting to go to the Maldives. This was not unusual. he wanted many things. He wanted coffee before breakfast, breakfast before he was hungry, and sometimes a new watch simply because he had seen a photograph of one in a magazine. He wanted things because they were beautiful. He wanted things because they were useful. And sometimes he wanted things because, for reasons known only to the strange machinery inside a human head, he wanted them. <br><br>The Maldives was different. The thought had arrived quietly that morning. It had not knocked. It had simply walked into his bedroom, sat down at the end of his enormous bed, and crossed its legs. Maldives. he opened his eyes. He stared at the ceiling. He could see it already. Blue water. White sand. A little wooden path over the sea. A cold drink sweating in a glass. He could almost feel the warm air on his face.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 37px; left: 786px; height: 360px;">And then, just as quickly, he remembered that he had been there twenty-three years ago. That was the trouble. He did not want to go to the Maldives. He wanted to go back to the Maldives. There was a difference. he knew this. He was a clever man. He had built companies, bought houses, sold companies, bought more houses, and once spent forty minutes explaining to an architect why a swimming pool should be shaped like a swimming pool rather than something called "an aquatic experience." <br><br>He knew the difference between wanting something and wanting what something had once made him feel. Still, he wanted to go. He reached for his phone. His thumb hovered over the screen. There was a travel application already installed. It was a dangerous little thing. With three taps, he could have a private plane, a villa, a boat, a chef, and a man whose entire job was apparently to place flowers in exactly the right places. He could be in the Maldives by tomorrow. He smiled. Then he put the phone down. "No," he said. </div>`;

vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 46px; left: 405px; font-size: 26px;">Chalon</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 88px; left: 406px; height: 360px; font-size: 13px;">Se despertó con ganas de ir a las Maldivas. No era algo inusual. Deseaba muchas cosas. Quería café antes del desayuno, desayunar antes de sentir hambre y, a veces, un reloj nuevo simplemente porque había visto una fotografía de uno en una revista. Deseaba cosas porque eran hermosas. Deseaba cosas porque eran útiles. Y, a veces, deseaba cosas porque —por razones que solo conoce el extraño mecanismo que opera dentro de la cabeza humana— simplemente las deseaba. <br><br>Lo de las Maldivas era distinto. La idea había llegado sigilosamente aquella mañana. No había llamado a la puerta. Simplemente había entrado en el dormitorio, se había sentado a los pies de su enorme cama y había cruzado las piernas. Maldivas. Abrió los ojos. Se quedó mirando el techo. Ya podía verlo todo: aguas azules, arena blanca, una pequeña pasarela de madera sobre el mar, una bebida fría condensándose en el vaso. Casi podía sentir el aire cálido en el rostro.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 37px; left: 786px; height: 360px;"> Y entonces, con la misma rapidez, recordó que había estado allí hacía veintitrés años. Ese era el problema. No quería ir a las Maldivas. Quería volver a las Maldivas. Había una diferencia; él lo sabía. Era un hombre inteligente. Había fundado empresas, comprado casas, vendido empresas, comprado más casas y, en una ocasión, pasó cuarenta minutos explicándole a un arquitecto por qué una piscina debía tener forma de piscina en lugar de algo llamado «una experiencia acuática».<br><br>Sabía distinguir entre querer algo y querer lo que aquello le había hecho sentir en otro tiempo. Aun así, quería irse. Buscó el teléfono. El pulgar se quedó suspendido sobre la pantalla. Ya tenía instalada una aplicación de viajes. Era una pequeña herramienta peligrosa. Con tres toques podía conseguir un avión privado, una villa, un barco, un chef y un hombre cuyo único trabajo consistía, al parecer, en colocar flores en los lugares exactos. Podría estar en las Maldivas mañana mismo. Sonrió. Luego dejó el teléfono. «No», dijo.</div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];

vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 46px; left: 405px; font-size: 26px;">Rodeo</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 88px; left: 406px; height: 360px; font-size: 13px;">Iba a ir a las Maldivas. Había tomado esa decisión un martes. Para el miércoles, ya no estaba seguro de si iba a ir. Aquello se estaba convirtiendo en un problema. No es que no pudiera ir; podía hacerlo cuando quisiera. Podía marcharme mañana por la mañana, esta misma noche o a mitad del almuerzo si de repente me aburría de estar comiendo. Ese era precisamente el problema. Nada me lo impedía. Nada, salvo todo lo demás. Llevaba semanas pensando en las Maldivas. Recordaba las fotografías: arena blanca, aguas azules, esas casitas ridículas sobre pilotes encima del mar. El tipo de lugar que parecía falso incluso cuando era real. Quería tumbarme allí y no hacer absolutamente nada. Quería nadar. Quería leer un libro. Quería levantarme tarde. Quería desaparecer una temporada. El inconveniente era que también quería hacer otras seiscientas cosas aproximadamente. Estaba el proyecto de la universidad. Había una idea de negocio que rondaba mi cabeza. Tenía un amigo que quería montar una empresa y otro que quería dejar la universidad. Había un tercer amigo que había roto con su pareja y había decidido que aquello era, de algún modo, problema mío. </div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"> Había gente a la que apenas conocía que quería consejos. Había gente a la que conocía muy bien que quería dinero. Había gente que no quería ni dinero ni consejos, pero que de alguna manera terminaba recibiendo ambas cosas. Y luego estaban mis propias ideas. Esas eran las peores. Mis propias ideas no dejaban de multiplicarse. Podía montar una empresa. Podía estudiar algo completamente distinto. Podía viajar por Sudamérica. Podía comprarme una casa en algún sitio. Podía aprender a navegar. Podía rodar una película. Podía desaparecer seis meses y volver con un aire misterioso. Podía irme a las Maldivas. Podía no hacer nada. No hacer nada resultaba especialmente tentador. Nunca se me había dado especialmente bien. Aquella mañana abrí el portátil para reservar el vuelo. Busqué «Maldivas». Luego vi un artículo sobre un nuevo programa universitario en Singapur. Lo abrí. Veinte minutos más tarde estaba leyendo sobre un curso totalmente diferente. Después estuve mirando apartamentos en Singapur. Luego, universidades en Londres. Más tarde vi un vídeo sobre un hombre que había fundado una empresa de zapatos hechos con hongos. Me pareció algo ridículo.</div>`;


vte[vte.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 46px; left: 405px; font-size: 26px;">Rodeo</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 101px; left: 406px; height: 360px;">I was going to the Maldives. I had decided this on a Tuesday. By Wednesday I had not decided whether I was going to the Maldives. This was becoming a problem. It was not that I could not go. I could go whenever I wanted. I could leave tomorrow morning, or tonight, or in the middle of lunch if I suddenly became bored with lunch. That was the whole problem. There was nothing stopping me. Nothing except everything else. I had been thinking about the Maldives for weeks. I remembered the photographs. White sand, blue water, those ridiculous little houses sitting on stilts above the sea. The sort of place that looked fake even when it was real. I wanted to lie there and do absolutely nothing. I wanted to swim. I wanted to read a book. I wanted to wake up late. I wanted to disappear for a while. The trouble was that I also wanted to do approximately six hundred other things. There was the university project. There was a business idea I had been thinking about. There was a friend who wanted to start a company. There was another friend who wanted to quit university.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 37px; left: 786px; height: 360px;"> There was a third friend who had broken up with someone and had decided that this was somehow my problem. There were people I barely knew who wanted advice. There were people I knew very well who wanted money. There were people who wanted neither money nor advice but had somehow ended up getting both. And then there were my own ideas. Those were the worst. My own ideas kept multiplying. I could start a company. I could study something completely different. I could travel around South America. I could buy a house somewhere. I could learn to sail. I could make a film. I could disappear for six months and come back looking mysterious. I could go to the Maldives. I could do nothing. Doing nothing was especially tempting. I had never been particularly good at it. That morning, I opened my laptop to book the flight. I searched for Maldives. Then I saw an article about a new university program in Singapore. I opened it. Twenty minutes later I was reading about a completely different course. Then I was looking at apartments in Singapore. Then I was looking at universities in London. Then I was watching a video about a man who had started a company making shoes from mushrooms. I thought this was ridiculous.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];


vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 46px; left: 405px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;">Entonces pensé que los zapatos eran, en realidad, bastante buenos. Luego pensé que tal vez debería fabricar zapatos. Así funcionaba mi vida. Se abría una puerta. Yo la atravesaba. Entonces veía otras diez puertas. Así que me quedaba allí, contemplándolas todas. Las Maldivas desaparecían. Luego alguien me llamaba. Contestaba. Era un amigo. Le habían ofrecido un trabajo. Quería saber si debía aceptarlo. Le dije que lo aceptara. Entonces preguntó por qué. Le di una respuesta larga. Luego preguntó qué haría yo. Le dije que probablemente haría otra cosa. Hubo silencio. «Haces que todo parezca fácil», dijo. Me reí. No era fácil. Eso era lo extraño. La gente pensaba que tener dinero facilitaba las decisiones. A veces, las hacía imposibles. Si solo había dos opciones, podías elegir una. Si había cien opciones, también podías elegir una. Pero si no había consecuencias reales por elegir mal, cada elección empezaba a parecer temporal. Siempre podías cambiar de opinión. Siempre podías irte. Siempre podías comprar la otra cosa. Siempre podías ir a otro sitio. Así que nunca llegabas realmente a ninguna parte. Aquella tarde fui al campus. Me dije a mí mismo que iba a trabajar. En su lugar, encontré a tres personas discutiendo fuera de un aula. Me detuve. Ese fue mi primer error. </div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"> Discutían sobre una asociación estudiantil. Yo no pertenecía a dicha asociación. No sabía de qué trataba la discusión. Aun así, escuché. Entonces, uno de ellos me preguntó qué opinaba. Se lo dije. Escucharon. Luego me pidieron ayuda. Acepté. Ese fue mi segundo error. A las cinco, de alguna manera, yo estaba a cargo de solucionar el problema. A las seis, estaba sentado en una cafetería con cuatro personas que había conocido ese mismo día. A las siete, habíamos elaborado un plan. A las ocho, el plan se había convertido en una reunión. A las nueve, la reunión se había transformado en otra reunión. A las diez, había prometido hablar con alguien que conocía a alguien que conocía a la persona que había causado el problema original. A las once, me acordé de las Maldivas. Abrí el teléfono. El vuelo seguía ahí. Un toque. Eso era todo. Lo miré. Entonces sonó el teléfono. Era mi madre. Quería saber dónde estaba. Se lo dije. Preguntó por qué. Se lo expliqué. Dijo que me estaba metiendo en asuntos que no tenían nada que ver conmigo. Tenía razón. Odiaba cuando eso sucedía. A la mañana siguiente, decidí marcharme. Preparé una bolsa. Metí camisas. Pantalones cortos. Gafas de sol. Un libro. Otro libro, porque no lograba decidirme por cuál.</div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 46px; left: 405px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">Then I thought the shoes were actually quite good. Then I thought perhaps I should make shoes. This was how my life worked. A door opened. I walked through it. Then I saw ten more doors. So I stood there looking at all of them. The Maldives disappeared. Then someone called me. I answered. It was my friend. He had been offered a job. He wanted to know whether he should take it. I told him to take it. Then he asked why. I gave him a long answer. Then he asked what I would do. I told him I would probably do something else. There was silence. "You make everything sound easy," he said. I laughed. It wasn't easy. That was the strange thing. People thought having money made decisions easier. Sometimes it made them impossible. If there were only two choices, you could choose one. If there were a hundred choices, you could still choose one. But if there were no real consequences to choosing badly, every choice began to feel temporary. You could always change your mind. You could always leave. You could always buy the other thing. You could always go somewhere else. So you never really arrived anywhere. That afternoon I went to campus. I told myself I was going to work.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Instead I found three people arguing outside a lecture hall. I stopped. This was my first mistake. They were arguing about a student society. I did not belong to the society. I did not know what the argument was about. I listened anyway. Then one of them asked what I thought. I told them. They listened. Then they asked me to help. I said yes. This was my second mistake. By five o'clock I was somehow in charge of fixing the problem. By six I was sitting in a café with four people I had met that day. By seven we had created a plan. By eight the plan had become a meeting. By nine the meeting had become another meeting. By ten I had promised to speak to someone who knew someone who knew the person who had caused the original problem. At eleven I remembered the Maldives. I opened my phone. The flight was still there. One tap. That was all. I looked at it. Then my phone rang. It was my mother. She wanted to know where I was. I told her. She asked why. I explained. She said I was getting involved in things that had nothing to do with me. She was right. I hated when that happened. The next morning I decided I would leave. I packed a bag. I put in shirts. Shorts. Sunglasses. A book. Another book, because I could not decide which one.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];



vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 46px; left: 405px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;"> Luego añadí otro, porque de repente pensé que tal vez quería algo más serio. Después saqué dos libros. Luego volví a meter uno. Aquello estaba llevando demasiado tiempo. Cerré la cremallera de la bolsa. Me iba. Por fin. Realmente me iba. Entonces recibí un mensaje. La asociación de estudiantes tenía un problema. Un problema grave. Al parecer, alguien había enviado un correo electrónico a la persona equivocada. Lo leí. No era problema mío. Lo leí de nuevo. Seguía sin ser problema mío. Dejé el teléfono. Lo volví a coger. Ese fue mi tercer error. A la hora de comer, ya no iba a ir a las Maldivas. Iba a asistir a una reunión. Por la tarde, iba a otra reunión. A medianoche, intentaba resolver una discusión entre dos personas que habían olvidado el motivo de su disputa. En algún momento, alguien derramó una taza de café entera sobre un portátil. Nadie sabía de quién era el portátil. Aquello se convirtió en la cuestión más importante de la sala. Luego alguien acusó a otra persona. Después alguien lloró. Luego alguien se rio. Después todos se rieron. Yo también me reí. Era totalmente absurdo. Las Maldivas habían quedado atrás. No para siempre. Nada era para siempre. Ese era el problema. El vuelo siempre se podía reservar más tarde. Siempre habría otra playa.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;">Otra isla. Otro verano. Otra oportunidad. Otra versión de mí que por fin tomaría la decisión correcta. Regresé a casa a las tres de la mañana. Al día siguiente, parecía que toda la universidad se había enterado del incidente del café. La gente no dejaba de felicitarme por haber resuelto un problema que yo no había creado. Alguien me preguntó si pensaba presentarme a las elecciones del consejo estudiantil. Dije que no. Luego lo pensé. Después dije que tal vez. Entonces me odié un poco. Volví a casa. Abrí el portátil. Busqué vuelos. Las Maldivas seguían ahí. Me quedé mirando la pantalla. Podía irme. Podía marcharme. Podía reservar el vuelo en ese mismo instante. Pero sabía lo que pasaría. Si iba a las Maldivas, pasaría el primer día preguntándome si debería haberme quedado. Si me quedaba, pasaría el primer día preguntándome si debería haberme ido. Quizás eso era la libertad en realidad: no la ausencia de cadenas, sino tener demasiados caminos. Cerré el portátil. No me sentía triste. Eso me sorprendió. No había ido a las Maldivas. No había ocurrido nada terrible. Nadie había muerto. Nadie lo había perdido todo. Simplemente no me había marchado porque había pasado demasiado tiempo interesándome por todo lo demás. Era una razón estúpida.</div>`;


vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 46px; left: 405px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">Then another one because I suddenly thought I might want something more serious. Then I removed two books. Then I put one back. This was taking too long. I zipped the bag. I was going. Finally. I was actually going. Then I received a message. The student society had a problem. A serious problem. Apparently someone had sent an email to the wrong person. I read it. It was not my problem. I read it again. It was still not my problem. I put my phone down. I picked it up. This was my third mistake. By lunchtime I was no longer going to the Maldives. I was going to a meeting. By the evening I was going to another meeting. By midnight I was trying to solve an argument between two people who had both forgotten what they were arguing about. At some point someone spilled an entire cup of coffee onto a laptop. Nobody knew whose laptop it was. This became the most important question in the room. Then someone accused someone else. Then someone cried. Then someone laughed. Then everybody laughed. I laughed too. It was completely absurd. The Maldives was gone. Not forever. Nothing was ever forever. That was the problem. The flight could always be booked later. There would always be another beach. </div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Another island. Another summer. Another opportunity. Another version of me who would finally make the right decision. I went home at three in the morning. The next day, the whole university seemed to have heard about the coffee incident. People kept congratulating me on solving a problem I had not created. Someone asked me if I was going to run for student council. I said no. Then I thought about it. Then I said maybe. Then I hated myself a little. I went home. I opened my laptop. I searched for flights. The Maldives was still there. I stared at the screen. I could go. I could leave. I could book the flight now. But I knew what would happen. If I went to the Maldives, I would spend the first day wondering whether I should have stayed. If I stayed, I would spend the first day wondering whether I should have gone. Maybe that was what freedom really was. Not having no chains. Having too many roads. I closed the laptop. I did not feel sad. That surprised me. I had not gone to the Maldives. Nothing terrible had happened. Nobody had died. Nobody had lost everything. I had simply failed to leave because I had spent too much time being interested in everything else. It was a stupid reason.</div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];


vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 38px; left: 785px; font-size: 26px;">Nimes</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;">Lo que lo convertía, de algún modo, en una razón muy buena. Salí a la calle. Había gente caminando. Un repartidor discutía con un guardia de seguridad. Un perro intentaba robarse un sándwich. Alguien se reía al otro lado de la calle. Pasó un autobús. El mundo estaba ocupado haciendo cosas sin pedirme ayuda. Por una vez, se lo permití. Me quedé allí un rato. <br><br> Luego, el perro consiguió el sándwich. Lo vi alejarse corriendo. Seguía deseando ir a las Maldivas. Probablemente siempre lo desearía. Pero desear estar en otro lugar no significaba que tuviera que ir allí. No hoy. Hoy estaba esta calle. Este perro ridículo. Este sándwich estúpido. Esta vida. Y, por el momento, no tenía ningún otro sitio donde estar.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 90px; left: 786px; height: 360px;">El hombre del despacho de la esquina intentaba hacer que la gente se moviera. No físicamente; eso habría sido más fácil. Intentaba hacer que se moviera el papeleo. La gente se movía todo el tiempo. Cambiaban de casa, de ciudad, de país, de departamento, de oficina, de escritorio. Se mudaban porque se habían casado o divorciado, porque los habían ascendido o despedido, porque habían tenido un hijo, porque odiaban su apartamento, porque les encantaba otro o simplemente porque habían decidido que las vistas desde su ventana actual ya no eran lo bastante buenas. El papeleo no se movía con tanta facilidad. Su empresa trasladaba a empleados por todo el mundo. O, al menos, eso era lo que se suponía que debía hacer. En realidad, lo que había eran hojas de cálculo, formularios y correos electrónicos. Había gente que enviaba el mismo documento a tres personas distintas porque nadie sabía cuál de ellas era la responsable. Había personas que necesitaban visados, personas que habían perdido el pasaporte, personas que intentaban encontrar colegio para sus hijos, personas que necesitaban un lugar donde vivir y personas que necesitaban un lugar donde vivir cerca de un colegio.</div>`;


vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 42px; left: 785px; font-size: 26px;">Nimes</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">Which made it, somehow, a very good reason. I went outside. There were people walking down the street. A delivery man was arguing with a security guard. A dog was trying to steal a sandwich. Someone was laughing on the other side of the road. A bus went past. The world was busy doing things without asking me to help. For once, I let it. I stood there for a while. Then the dog got the sandwich. I watched it run away. I still wanted the Maldives. I probably always would. But wanting somewhere else did not mean I had to go there. Not today. Today there was this street. This ridiculous dog. This stupid sandwich. This life. And, for the moment, I had nowhere else to be.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 95px; left: 786px; height: 360px;">The man in the corner office was trying to make people move. Not physically. That would have been easier. He was trying to make their paperwork move. People moved all the time. They moved houses, cities, countries, departments, offices, desks. They moved because they had married someone, divorced someone, been promoted, been fired, had a baby, hated their apartment, loved another apartment, or simply decided that the view from their current window was no longer good enough. The paperwork did not move so easily. His company relocated employees around the world. At least, that was what the company was supposed to do. In reality, there were spreadsheets. There were forms. There were emails. There were people sending the same document to three different people because nobody knew which of the three people was responsible for it. There were people who needed visas. People who had lost passports. People who were trying to find schools for their children. People who needed somewhere to live. People who needed somewhere to live near a school. </div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];



vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 38px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;">Personas que necesitaban vivir cerca de una escuela, pero no de la oficina, porque sus maridos trabajaban en otro lugar. Cada persona tenía un motivo. Cada motivo se convertía en una casilla. Cada casilla se convertía en otra casilla. Él había empezado a desarrollar un programa informático para que todo aquello resultara menos absurdo. No esperaba gran cosa de ello. En parte, por eso había funcionado tan bien.<br> Cuando alguien espera llegar a ser importante, cualquier pequeño éxito se convierte en una prueba. Cuando alguien no espera nada, un pequeño éxito es simplemente algo útil. A él le gustaban las cosas útiles. El programa había comenzado como un proyecto paralelo. Luego alguien lo utilizó. Después, otra persona lo usó. Más tarde, su jefe le pidió que lo mejorara. Luego, alguien de otro departamento preguntó si también podían utilizarlo. Después, un director le pidió que hiciera una demostración. Más tarde, tres directores le pidieron una demostración. Él siguió trabajando. No se decía a sí mismo que aquella fuera su gran oportunidad. No se decía que aquello cambiaría su vida. Sobre todo, se decía que la interfaz tenía mal aspecto. Así que arregló la interfaz. Había un botón al que se llegaba tras tres clics; hizo que bastara con uno solo.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;"> Había un formulario que solicitaba información que nadie necesitaba. Él lo eliminó. Había una notificación que decía algo así como: «Su flujo de trabajo de reubicación ha encontrado una excepción». Él lo cambió por: «Algo salió mal». La gente prefería esto. Él también. A la hora del almuerzo, una mujer de Recursos Humanos se acercó a su escritorio. Necesitaba algo. Siempre necesitaba algo. <br class=""><br> «¿Puedes revisar esto?». Él miró la pantalla. Era una solicitud de reubicación de un empleado que se mudaba a Berlín. La revisó. El empleado había olvidado subir un documento. Envió un mensaje. La mujer le dio las gracias. Se marchó. Diez minutos después, regresó. El empleado había encontrado el documento. Ahora el sistema no lo aceptaba. Él lo solucionó. Ella volvió a darle las gracias. Él retomó su trabajo. En eso consistía la mayor parte de su vida. Alguien necesitaba algo. <br><br> Intentó simplificarlo. Otra persona necesitaba algo. Lo intentó de nuevo. No había ninguna gran teoría detrás de ello. Al menos, no una que él hubiera puesto por escrito.</div>`;


vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 42px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">People who needed somewhere to live near a school but not near the office because their husband worked somewhere else. Every person had a reason. Every reason became a box. Every box became another box. He had begun building software to make all of this less ridiculous. He had not expected much from it. That was partly why it had gone so well.<br><br> When a person expects to become important, every small success becomes evidence. When a person expects nothing, a small success is simply useful. He liked useful things. The software had started as a side project. Then someone used it. Then someone else used it. Then his manager asked him to improve it. Then someone from another department asked if they could use it too. Then a director asked him to demonstrate it. Then three directors asked him to demonstrate it. He kept working. He did not tell himself that this was the big break. He did not tell himself that it would change his life. He mostly told himself that the interface looked ugly. So he fixed the interface. There was a button that took three clicks to reach. He made it one click. </div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 786px; height: 360px;">There was a form that asked for information nobody needed. He removed it. There was a notification that said something like, "Your relocation workflow has encountered an exception." He changed it to: "Something went wrong." People preferred this. He did too. At lunch, a woman from Human Resources came to his desk. She needed something. She always needed something.  <br><br> "Can you check this?" He looked at the screen. It was a relocation request from an employee moving to Berlin. He checked it. The employee had forgotten to upload one document. He sent a message. The woman thanked him. She left. Ten minutes later she came back. The employee had found the document. Now the system would not accept it. He fixed it. She thanked him again. He went back to work. This was most of his life. Someone needed something. <br><br> He tried to make it easier. Someone else needed something. He tried again. There was no grand theory behind it. At least, not one he had written down.</div>`;



dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];


vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 38px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;">Quería tomarse unas vacaciones. Llevaba meses pensando en ello. A veces, mientras trabajaba, miraba una fotografía en su teléfono. Una playa. El mar. Un lugar cálido. No había reservado nada. Ni siquiera sabía exactamente cuándo iría. Siempre había algo que terminar primero. Esto no le molestaba tanto como debería. Sabía que el software podía fallar. Sabía que podía tener éxito. Sabía que, si tenía éxito, otra persona podría llevarse el mérito. <br><br> Sabía que, si fallaba, alguien podría decir que le había advertido. Todas estas cosas eran posibles. Aun así, trabajaba. Había algo agradable en el trabajo cuando dejaba de preguntarse en qué se convertiría. Escribes algo. Lo pruebas. Se rompe. Lo arreglas. Alguien se queja. Escuchas. Arreglas otra cosa. El día avanza. Tú avanzas con él. Quizás a esto era a lo que la gente llamaba «fluir».<br> Había oído esa palabra antes: fluir. Sonaba a algo inventado por un hombre con pantalones de lino. Pero la idea en sí era sencilla. Hacías el trabajo. Dejabas de intentar forzar el futuro para que adoptara una forma concreta.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Dejaba que lo siguiente fuera simplemente lo siguiente. No siempre se le daba bien eso. A nadie se le daba bien. A veces imaginaba el contrato. El gran contrato. Aquel que todos esperaban. Imaginaba a alguien estrechándole la mano. Imaginaba su nombre en una presentación. Imaginaba el software siendo utilizado por miles de personas. Entonces se sorprendía a sí mismo imaginándolo y se reía. <br>«A trabajar», se decía. Y volvía al trabajo. El jueves, el software dejó de funcionar. No del todo; eso habría sido más sencillo. Dejó de funcionar de una manera que carecía de sentido. Los usuarios podían iniciar sesión. Podían subir documentos. Podían ver sus expedientes de reubicación. Simplemente no podían completarlos. El botón final no hacía nada. Se quedó mirándolo. Hizo clic. Nada. Volvió a hacer clic. Seguía sin pasar nada. Se quedó mirando la pantalla. Luego se rio. Claro. Siempre era el botón final.<br> El botón final era el lugar donde el software se ponía filosófico.<br><br> Se quedó hasta tarde. A las nueve, la oficina estaba casi vacía. A las diez, estaba completamente vacía. A las once, el guardia de seguridad pasó junto a su escritorio. «¿Te vas a casa?». «En un rato». El guardia asintió y siguió caminando.</div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 42px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">He had a holiday he wanted to take. He had been thinking about it for months. Sometimes, while working, he would look at a photograph on his phone. A beach. A sea. Somewhere warm. He had not booked anything. He did not even know exactly when he would go. There was always something to finish first. This did not bother him as much as it should have. He knew that the software might fail. He knew it might succeed. He knew that if it succeeded, someone else might take credit. <br class=""> He knew that if it failed, someone might say they had warned him. All of these things were possible. He worked anyway. There was something pleasant about the work when he stopped asking what it would become. You write the thing. You test the thing. It breaks. You fix the thing. Someone complains. You listen. You fix another thing. The day moves. You move with it. Perhaps this was what people meant by flow.<br> He had heard the word before. Flow. It sounded like something invented by a man wearing linen trousers. But the idea itself was simple. You did the work. You stopped trying to wrestle the future into a particular shape.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 786px; height: 360px;">You let the next thing be the next thing. He was not always good at this. Nobody was. Sometimes he imagined the contract. The big one. The one everyone had been waiting for. He imagined someone shaking his hand. He imagined his name on a presentation. He imagined the software being used by thousands of people. Then he would notice himself imagining it and laugh. <br>"Back to work," he would say. So he went back to work. On Thursday, the software stopped working. Not completely. That would have been simpler. It stopped working in a way that made no sense. People could log in. They could upload documents. They could see their relocation cases. They simply could not finish them. The final button did nothing. He stared at it. He clicked it. Nothing. He clicked it again. Still nothing. He stared at the screen. Then he laughed. Of course. It was always the final button.<br> The final button was where software went to become philosophical.<br><br> He stayed late. At nine, the office was mostly empty. At ten, it was completely empty. At eleven, the security guard passed his desk. "You going home?" "In a bit." The guard nodded. He continued walking.</div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];

vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 38px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;">A medianoche, el botón funcionó. Cerró el portátil. Se fue a casa. A la mañana siguiente, había un correo electrónico. La empresa quería una reunión. Supuso que algo se había vuelto a estropear. En cambio, había seis personas en la llamada. Habían utilizado el software. Querían hablar de un contrato de mayor envergadura. Él escuchó.<br> Respondió a las preguntas. Les mostró cómo funcionaba el sistema. Preguntaron con qué rapidez se podía ampliar. Él se lo dijo. Preguntaron cuánto costaría. Preguntaron si podría llevarlo a cabo. Dijo que sí. Podía hacerlo. La reunión terminó.<br> Cerró el portátil. No ocurrió nada. Le pareció extraño. Esperaba que sucediera algo. Una sensación. Un subidón repentino. Quizás música. No hubo música. Solo se oía el zumbido del aire acondicionado.<br>Fue a buscar café. Dos horas más tarde, llegó otro correo electrónico. El contrato había sido aprobado. Lo leyó una vez. Luego una segunda. Después, se recostó en la silla. Sonrió. Eso fue todo. La mujer de Recursos Humanos apareció en su escritorio. Necesitaba ayuda. Él la miró. Luego miró el correo electrónico. Y volvió a mirarla a ella.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">—¿Qué pasó? —preguntó ella. —Lo conseguimos. —¿El contrato? —Él asintió. Ella sonrió. Luego, de inmediato, preguntó si la nueva versión podía gestionar empleados con personas a su cargo. Él se rio.<br> —Probablemente.<br>Ella se quedó allí. Él abrió el programa. Empezaron a trabajar. Tres semanas después, el nuevo sistema estaba en marcha. La gente se trasladaba. Los documentos circulaban. Los visados ​​se tramitaban. Las familias se mudaban.<br><br>El mundo seguía siendo complicado, pero un poco menos que antes. Un viernes por la tarde, cerró el portátil. Había terminado. No para siempre; nada terminaba nunca para siempre. Pero había concluido el trabajo del día. Sacó el teléfono. La fotografía seguía allí. La playa. El agua azul. Las casitas sobre el mar. La contempló. Luego abrió un sitio web de viajes. Esta vez no se planteó si debía estar haciendo otra cosa. Reservó el billete. A la mañana siguiente preparó una maleta. No llevó gran cosa: unas cuantas camisas, un libro, gafas de sol, un par de zapatos. Eso bastaba. En el aeropuerto, se sentó junto a la ventana y observó cómo los aviones iban y venían.</div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 42px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">At midnight, the button worked. He shut the laptop. He went home. The next morning there was an email. The company wanted a meeting. He assumed something had broken again. Instead, there were six people on the call. They had used the software. They wanted to discuss a larger contract. He listened.<br> He answered questions. He showed them how the system worked. They asked how quickly it could be expanded. He told them. They asked what it would cost. They asked if he could deliver it. He said yes. He could. The meeting ended.<br> He closed the laptop. Nothing happened. This seemed strange. He had expected something to happen. A feeling. A sudden rush. Perhaps music. There was no music. There was only the hum of the air conditioner. <br><br>He went to get coffee. Two hours later, another email arrived. The contract was approved. He read it once. Then twice. Then he leaned back in his chair. He smiled. That was all.<br> The woman from Human Resources appeared at his desk. She needed help. He looked at her. Then at the email. Then back at her.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 786px; height: 360px;">"What happened?" she asked. "We got it." "The contract?" He nodded. She smiled. Then she immediately asked whether the new version could handle employees with dependants. He laughed.<br> "Probably." <br>She stood there. He opened the software. They began working. Three weeks later, the new system was running. People moved. Documents moved. Visas moved. Families moved. <br><br>The world continued to be complicated, but it was slightly less complicated than before. One Friday afternoon, he closed his laptop. He had finished. Not forever. Nothing was ever finished forever. But he had finished today's work. He took out his phone. The photograph was still there. The beach. The blue water. The little houses over the sea. He looked at it. Then he opened a travel website. This time he did not think about whether there was something else he should be doing. He booked the ticket. The next morning he packed one bag. He did not pack much. A few shirts. A book. Sunglasses. A pair of shoes. That was enough. At the airport, he sat by the window and watched planes come and go.</div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];
vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 38px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 39px; left: 406px; height: 360px; font-size: 13px;">La gente se apresuraba. Llamaban a sus familias. Perdían los pasaportes. Alguien perdió a un niño durante unos treinta segundos y luego lo encontró comiendo una galleta junto a una máquina expendedora. Un hombre intentaba meter una maleta enorme en un coche diminuto. La maleta ganó. <br><br> Su teléfono vibró. Un mensaje del trabajo. Luego guardó el teléfono. Por una vez, otra persona podía resolverlo. <br><br> El avión despegó. Abajo, la ciudad se hacía más pequeña. Pensó en el software. Se preguntó cómo funcionaría sin él. Se preguntó si el nuevo contrato daría lugar a otro. Se preguntó si aquello era el comienzo de algo. Luego dejó de preguntarse. Ya habría tiempo para todo eso más adelante. Por ahora, solo estaba el vuelo. Las nubes. El extraño silencio de estar entre dos lugares. Y, en algún punto más adelante, un mar que había querido ver. <br> Cuando por fin llegó, el agua era exactamente tan azul como se veía en la fotografía. Quizás incluso más azul. Se quedó de pie en la orilla de la playa.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Había imaginado este momento muchas veces. No fue exactamente como lo había imaginado. Fue mejor. No porque el mar fuera perfecto. No lo era. <br> Había gente riendo cerca. Un niño lloraba. Alguien sacaba demasiadas fotos. Un camarero dejó caer un vaso. El viento soplaba con más fuerza de la que él esperaba. Era real. <br> Entró en el agua. A sus espaldas, el mundo seguía su curso sin él. La gente necesitaba cosas. La gente perdía cosas. La gente construía cosas. La gente se preocupaba. La gente triunfaba. La gente fracasaba. El software seguía en marcha. El contrato estaba firmado. El futuro aguardaba. Pero nada de eso estaba allí. <br> Allí estaba el agua. Allí estaba el sol. Allí estaba la arena bajo sus pies. Y siguió caminando.</div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 42px; left: 785px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 407px; height: 360px;">People hurried. People called their families. People lost passports. Someone had lost a child for approximately thirty seconds and then found him eating a biscuit beside a vending machine. A man was trying to fit an enormous suitcase into a tiny car. The suitcase won. <br><br> His phone buzzed. A message from work. Then he put the phone away. For once, someone else could solve it. <br><br> The plane took off. Below him, the city became smaller. He thought about the software. He wondered how it would perform without him. He wondered whether the new contract would lead to another contract. He wondered whether this was the beginning of something. Then he stopped wondering. There would be time for all that later. For now there was only the flight. The clouds. The strange quiet of being between places. And, somewhere ahead, a sea he had wanted to see. <br> When he finally arrived, the water was exactly as blue as it had looked in the photograph. Perhaps even bluer. He stood at the edge of the beach. </div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 786px; height: 360px;">He had imagined this moment many times. It was not quite the same as he had imagined. It was better. Not because the sea was perfect. It wasn't. <br> There were people laughing nearby. A child was crying. Someone was taking too many photographs. A waiter dropped a glass. The wind was stronger than he expected. It was real. <br>He walked into the water. Behind him, the world continued without him. People needed things. People lost things. People built things. People worried. People succeeded. People failed. The software was running. The contract was signed. The future was waiting. But none of it was here. <br>Here was the water. Here was the sun. Here was the sand beneath his feet. Then he kept walking.</div>`;



dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];

vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 49px; left: 403px; font-size: 26px;">Chalon</div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 92px; left: 406px; height: 360px; font-size: 13px;">El dormitorio era enorme. Contenía una cama lo suficientemente grande para una familia pequeña, dos sillones en los que nadie se sentaba nunca y un cuadro que costaba más que la mayoría de las casas. Ninguna de esas cosas le respondió. Se levantó de la cama. Caminó hacia la ventana. Su casa se alzaba en una gran extensión de terreno, tras unas puertas altas. Había árboles, jardines, fuentes y un largo camino de entrada que serpenteaba como si quisiera hacer una entrada triunfal. La mañana estaba gris. Un jardinero podaba un seto. Un pájaro se posó en el seto y lo observó. Él observó al pájaro. El pájaro lo observó a él. <br><br> El pájaro parecía perfectamente feliz. Eso le irritó ligeramente. «Tú no estás pensando en las Maldivas», dijo. El pájaro se alejó volando. Le pareció un gesto bastante grosero. Bajó las escaleras. El desayuno le esperaba. Había huevos, fruta, tostadas, café, té, zumo y varias cosas más que habían puesto en la mesa porque alguien en la cocina creía que los ricos necesitaban más opciones. Se sentó. Miró el café. Miró los huevos. Miró las tostadas.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Seguía pensando en las Maldivas. Suspiró. Entonces recordó la playa. Veintitrés años atrás, él era más joven. Mucho más joven. Por aquel entonces era un insensato. Había sido feliz de una manera que solo los insensatos y los ancianos logran a veces.<br class=""> Había viajado a las Maldivas con una mujer a la que amaba. Habían reído sin motivo aparente. Habían cenado descalzos. Habían nadado de noche. Habían permanecido despiertos hasta el amanecer. Recordaba el amanecer con especial nitidez. El cielo se había teñido de rosa. Luego de naranja. Después, de dorado. <br>El mar parecía inmenso. Recordaba haber pensado que nada cambiaría jamás. Por supuesto, todo cambió. La gente siempre creía que nada cambiaría. Era uno de los muchos errores encantadores que cometían los seres humanos. <br><br>Volvió a tomar el teléfono. Buscó vuelos. Había muchas opciones. Podía marcharse el jueves. O el viernes. O esa misma noche. Podía reservar la isla entera si quería. Estuvo a punto de hacerlo. Pero se detuvo. «¿Qué estoy intentando hacer exactamente?», se preguntó.</div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 47px; left: 407px; font-size: 26px;">Chalon</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 103px; left: 407px; height: 360px;">The bedroom was enormous. It contained a bed large enough for a small family, two armchairs no one ever sat in, and a painting that cost more than most houses. None of these things answered him. he got out of bed. He walked to the window. His house stood on a great piece of land behind tall gates. There were trees, gardens, fountains and a long driveway that curved like it was trying to make an entrance. The morning was grey. A gardener was trimming a hedge. A bird sat on the hedge and watched him. he watched the bird. The bird watched him. <br><br> The bird seemed perfectly happy. This irritated him slightly. "You're not thinking about the Maldives," he said. The bird flew away. he thought this was rather rude. He went downstairs. His breakfast was waiting. There were eggs, fruit, toast, coffee, tea, juice and several other things that had been placed on the table because someone in the kitchen believed that rich people needed more choices. he sat down. He looked at the coffee. He looked at the eggs. He looked at the toast. Still Maldives. He sighed.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 62px; left: 784px; height: 360px;"> Then he remembered the beach. Twenty-three years ago, he had been younger. Much younger. He had been foolish then. He had been happy in a way that only foolish people and very old people sometimes manage.<br class=""> He had gone to the Maldives with a woman he loved. They had laughed for no particular reason. They had eaten dinner barefoot. They had swum at night. They had stayed awake until sunrise. he remembered the sunrise most clearly. The sky had turned pink. Then orange. Then gold. <br>The sea had looked enormous. He remembered thinking that nothing would ever change. Of course, everything changed. People always thought nothing would change. This was one of the many charming mistakes humans made. <br><br>he picked up his phone again. He searched for flights. There were plenty. He could leave on Thursday. Or Friday. Or tonight. He could book the whole island if he wished. He almost did. Then he stopped. "What exactly am I trying to do?" he asked.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];


vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 49px; left: 403px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 45px; left: 406px; height: 360px; font-size: 13px;">La habitación permaneció en silencio. «¿Irse de vacaciones?». Silencio. «¿O retroceder?». Más silencio. Dejó el teléfono. Esta vez se alejó de él. Durante siete minutos, todo estuvo bien. Entonces recordó otra cosa. Había un pequeño restaurante en las Maldivas. Había comido allí hacía veintitrés años. Quizás todavía existía. Se preguntó qué aspecto tendría ahora. Cogió el teléfono. Lo buscó. El restaurante había cambiado de dueño. Volvió a buscar. Había una fotografía. El edificio parecía distinto. Se sintió decepcionado. Luego se sintió ridículo por haberse sentido decepcionado. Después se sintió decepcionado por sentirse ridículo. Esto continuó durante un tiempo. A las once, decidió salir a caminar. Fue una decisión sensata. Se puso los zapatos. Luego decidió que necesitaba un par de zapatos nuevos. Volvió a subir. Abrió el armario. Había cuarenta y tres pares. Se quedó mirándolos. No necesitaba zapatos. Cerró el armario. Entonces pensó en comprar un coche nuevo. Había un coche en particular que había visto. Era extremadamente rápido. Era extremadamente caro. También era casi idéntico al coche que ya tenía. Se imaginó conduciéndolo. Imaginó el sonido. Imaginó la carretera. Imaginó la satisfacción de tener algo nuevo.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Entonces imaginó el coche aparcado en su garaje al cabo de tres semanas. Se conocía bien. Lo miraría. Lo admiraría. Luego se preguntaría qué comprar a continuación. Cerró los ojos. <br><br> Ahí estaba de nuevo. Ese pequeño impulso. Hacer algo. Comprar algo. Ir a algún sitio. Recordar algo. Cambiar algo. Mejorar algo. Moverse. Estaba de pie en el pasillo de su casa. Llevaba once años viviendo allí. De repente, se fijó en el suelo. Era de piedra clara. Había un pequeño arañazo cerca de la pared. Nunca antes se había dado cuenta. Se puso en cuclillas. El arañazo tenía una forma que recordaba vagamente a un pájaro. Lo tocó. Por alguna razón, aquello le pareció importante. No porque lo fuera. Precisamente por eso. Era solo un arañazo. No tenía por qué convertirse en nada. No tenía por qué recordarle nada. No tenía por qué conducir a ninguna parte. Simplemente estaba allí. Se puso en pie. Salió al exterior. El ambiente en el jardín ya era cálido. Había salido el sol. Un jardinero seguía recortando el seto. El mismo pájaro, o tal vez otro, estaba posado cerca.</div>`;


vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 47px; left: 407px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 407px; height: 360px;">The room remained silent. "Go on holiday?" Silence. "Or go backwards?" More silence. he put the phone down. This time he walked away from it. For seven minutes, everything was fine. Then he remembered something else. There was a small restaurant in the Maldives. He had eaten there twenty-three years ago. Perhaps it still existed. He wondered what it looked like now. He picked up his phone. He searched for it. The restaurant had changed owners. He searched again. There was a photograph. The building looked different. he felt disappointed. Then he felt foolish for being disappointed. Then he felt disappointed about feeling foolish. This went on for some time. At eleven o'clock, he decided to go for a walk. This was a sensible decision. He put on his shoes. Then he decided he needed a new pair of shoes. He returned upstairs. He opened a wardrobe. There were forty-three pairs. He stared at them. He did not need shoes. He closed the wardrobe. Then he thought about buying a new car. There was a particular car he had seen. It was extremely fast. It was extremely expensive. It was also almost exactly like the car he already owned. he imagined himself driving it. He imagined the sound. He imagined the road. He imagined the satisfaction of having something new.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 47px; left: 784px; height: 360px;">Then he imagined the car sitting in his garage after three weeks. He knew himself. He would look at it. He would admire it. Then he would wonder what to buy next. He closed his eyes. <br><br> There it was again. That little itch. Do something. Buy something. Go somewhere. Remember something. Change something. Improve something. Move. He was standing in his own hallway. He had lived in the house for eleven years. He suddenly noticed the floor. It was made of pale stone. There was a small scratch near the wall. He had never noticed it before. He crouched down. The scratch was shaped a little like a bird. he touched it. For some reason, this felt important. Not because it was important. That was precisely why. It was just a scratch. It did not need to become anything. It did not need to remind him of anything. It did not need to lead anywhere. It was simply there. he stood up. He walked outside. The garden was warm now. The sun had appeared. A gardener was still trimming the hedge. The same bird, or perhaps another bird, was sitting nearby. </div>`;



dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];

vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 49px; left: 403px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 45px; left: 406px; height: 360px; font-size: 13px;">Escuchaba su propia respiración. Por un instante, quiso volver a recordar las Maldivas. Se permitió hacerlo. Acudieron a su mente el agua azul, la arena blanca y la joven. Las risas. El amanecer. Era hermoso. No apartó el recuerdo, pero tampoco se sumergió en él. Dejó que permaneciera donde debía estar: a sus espaldas. Algo bueno que había sucedido. No una puerta. No un destino. Simplemente un recuerdo. Luego miró hacia el jardín. Una abeja se desplazaba de una flor a otra. El jardinero había dejado de podar el seto y bebía agua. Una hoja había caído en la fuente. El pájaro voló desde el muro hasta el césped. <br><br> En algún lugar de la casa, un reloj marcaba los segundos. Por un momento, pensó en las cosas que había hecho a lo largo de su vida. Le vino a la memoria aquella discusión en la asociación de estudiantes; aunque ya no recordaba el motivo, sí recordaba cómo todos habían reído después. También recordó el software de reubicación, si bien para entonces ya se había convertido en algo mucho mayor que el pequeño programa que él había creado tiempo atrás en su escritorio de la oficina.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;">Aquellas cosas parecían muy lejanas. Más lejanas que las Maldivas, de algún modo. Sonrió al pensar que aquel joven, tan convencido de que necesitaba estar en todas partes, había terminado pasando años facilitando que los demás llegaran a sus destinos. Se quedó allí sentado un buen rato. No ocurrió nada. Y, como no ocurrió nada, todo pareció suceder. El viento se movía entre los árboles. La luz cambiaba. La fuente seguía emitiendo su leve sonido. El jardinero volvió a su trabajo. La abeja desapareció. Inspiró. Luego espiró. No sintió ninguna gran revelación. No hubo truenos. Ni voces que bajaran del cielo. Ni ningún anciano misterioso que apareciera junto a la fuente para explicarle el sentido de la vida. Eso habría resultado inoportuno. En su lugar, solo estaban el jardín. Y él. Y aquel instante. Las Maldivas habían sido maravillosas. Siempre guardaría un grato recuerdo de aquella mañana de hace veintitrés años. Pero aquello no le estaba esperando. Había terminado. Le había dado lo que le tenía que dar. No necesitaba exprimirlo hasta sacarle algo más.</div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 47px; left: 407px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 407px; height: 360px;">He heard his own breathing. For a moment, he wanted to remember the Maldives again. He let himself remember. The blue water came. The white sand came. The young woman came. The laughter. The sunrise. It was beautiful. He did not push it away. But he did not climb inside it either. He let the memory sit where it belonged. Behind him. A good thing that had happened. Not a door. Not a destination. Just a memory. Then he looked at the garden. A bee was moving from one flower to another. The gardener had stopped trimming the hedge and was drinking water. A leaf had fallen into the fountain. The bird flew from the wall to the grass. <br><br> Somewhere in the house, a clock ticked. For a moment, he thought about the things he had done in life. The student society argument came back to him, though he could no longer remember what it had been about but he remembered how everyone had laughed afterwards. He remembered the relocation software too, though by now it had grown into something much larger than the little program he had once built at an office desk. </div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 47px; left: 784px; height: 360px;">These things seemed very far away. Farther away than the Maldives, somehow. He smiled at the thought that the young man who had been so certain he needed to be everywhere had eventually spent years making it easier for other people to get where they were going.  He sat there for a long time. Nothing happened. And because nothing happened, everything seemed to happen. The wind moved through the trees. The light changed. The fountain continued to make its little sound. The gardener went back to work. The bee disappeared. he breathed in. Then out. He felt no great revelation. There was no thunder. No voice from the sky. No mysterious old man appearing beside the fountain to explain the meaning of life. That would have been inconvenient. Instead, there was only the garden. And him. And this moment. The Maldives had been wonderful. He would always love that morning twenty-three years ago. But it was not waiting for him. It was finished. It had given him what it had given him. He did not need to squeeze it until it gave him something else.</div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];


vt[vt.length]=`<div id="text_88" class="textshirt mergershirt" style="top: 49px; left: 403px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_89" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 45px; left: 406px; height: 360px; font-size: 13px;">Extendió la mano para tomar el teléfono. Por un instante, pensó en reservar el vuelo. Luego abrió la cámara. Tomó una fotografía del jardín. La observó. No era una fotografía muy buena. La luz no era la adecuada. El seto se veía extraño. El pájaro era apenas un pequeño punto negro. Se rio. Después, guardó el teléfono.<br> La mañana dio paso a la tarde. La tarde se transformó en algo más suave. Y él, que habría podido comprar casi cualquier cosa, comprendió por fin algo muy sencillo. No necesitaba comprar el pasado. No necesitaba repetirlo. No necesitaba mejorar el presente convirtiéndolo en otro lugar. Solo necesitaba estar donde ya estaba. Así que estuvo allí. Y, por una vez, eso fue suficiente.</div>`;
vt[vt.length]=`<div id="text_90" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 786px; height: 360px;"></div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 47px; left: 407px; font-size: 26px;">&nbsp;</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 46px; left: 407px; height: 360px;">he reached for his phone. For one second, he thought he would book the flight. Then he opened the camera. He took a photograph of the garden. He looked at it. It was not a very good photograph. The light was wrong. The hedge looked strange. The bird was only a small black dot. he laughed. Then he put the phone away.<br> The morning became afternoon. The afternoon became something softer. And he, who could have bought almost anything, finally understood something very simple. He did not need to buy the past. He did not need to repeat it. He did not need to improve the present by turning it into somewhere else. He only needed to be where he already was. So he was. And for once, that was enough.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 47px; left: 784px; height: 360px;"></div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


export function openBoard(){
    jve.dbF.qr.initBook(dbset,drabindex);
}
