var vt = [];
var vte = [];
export var dbset = [];

var dbbtn = `<div id="dbbutton" class="textshirt dbbutton" style="top: 91.3769%; left: 95.4652%; width: 36px; height: 36px;"><div id="dbbutton2" class="dbbutton textshirt circleshirt" style="height: 36px; width: 36px; top: 91.3769%; left: 95.4652%; background-color: rgb(255, 255, 255); border-color: rgb(255, 255, 255); color: rgb(255, 255, 255);"></div><div id="dbbutton3" class="dbbutton textshirt circleshirt" style="height: 22px; width: 22px; top: 92.4896%; left: 96.0907%;"></div></div>`;

//to adjust
export const dbtitle = 'directorscut2';
const defaultspeed = 25;
const transws = ' wspeed_10';
const drabindex = 'directorscut2';

const bimgpath = storyline.jsonUrl+'./drawboard/bimg/openbook-581128.jpg';
var dbbg =`<div id="dbbackg" class="textshirt imageshirt" style="left: -14px; top: -72px; width: 1280px; height: 853px;"><img src="`+bimgpath+`"></div>`;
dbbg += '<style>.textshirt{color:#000;font-family:EBGaramond;}</style>';

vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">Llyod</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 94px; left: 407px; height: 360px;" contenteditable="false"><p>Llyod Reeves está escribiendo algo con un bolígrafo azul en una hoja de papel. Su escritura parece impecable, en cursiva en lugar de en letra de imprenta, fluyendo con naturalidad mientras anota cosas. Hacemos un alejamiento para mostrarlo en medio de un restaurante con mesas vacías.</p><div>FUNDIDO A: EXT. BARCO DE CRUCERO<br>Una vista del océano inmenso desde un crucero. Vemos las barandillas de acero y, más allá de ellas, una fina estela blanca que se extiende detrás del barco y se pierde en el azul, el único indicio de lo lejos que ya ha navegado.</div><div></div><div>CORTE A: EXT. BARCO DE CRUCERO, CUBIERTA SUPERIOR - CONTINUACIÓN. El rostro de Julie Raymond. La cámara se aleja para mostrarla dando un paseo pausado por el espacio abierto de la cubierta superior del barco. Parece más pensativa que alegre, a pesar de estar a bordo de un crucero de lujo.</div><p><span style="font-size:13px">DISOLVENCIA A: INT. OFICINA, DE DÍA. </span></p></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false"><p><span style="font-size:13px">Una sala de conferencias ESPECTACULAR, amplia y con paredes de cristal. Una mesa larga. Julie está sentada a ella, absorta en su trabajo. Su teléfono suena. Echa un vistazo a la pantalla: Dr. Reaper. Ella contesta. La cámara se desplaza hacia un rincón de la sala y la vemos escuchar. </span></p><p><span style="font-size:13px">CORTE A: INTERIOR DE UN RESTAURANTE CARO, DE NOCHE. </span></p><p><span style="font-size:13px">Una cita entre Julie y Llyod. Una conversación distendida entre dos personas que acaban de conocerse y que quieren saber más la una de la otra. A Llyod le gustan las enseñanzas sobre la manifestación y está probando algunas técnicas con varios aspectos de su vida, uno de ellos es un viaje en crucero.</span></p><p><span style="font-size:13px">«¿Por qué?», preguntó Julie.</span></p><p><span style="font-size:13px">«¿La verdad? Es un poco vergonzoso». Cuando tenía unos nueve años, mi abuelo nos envió una postal desde un crucero. En el reverso había una sola línea, algo así como: «El agua se extiende hasta el infinito y nadie te pide nada».</span></p></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">Llyod</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;" contenteditable="false"><p>Llyod Reeves is writing something with a blue pen on a piece of paper. His writings seems impeccable, cursive instead of print type. just flowing with things to write down. we zoomed out to a view of him in the middle of a restaurant with empty tables.</p><div>FADE TO: EXT. CRUISE SHIP<br>a view of the wide ocean from onboard a cruise ship, we see the steel railings, beyond the rail, a thin white wake trails behind the ship and goes into the blue, the only evidence of how far it has already traveled.</div><div></div><div>CUT TO: EXT. CRUISE SHIP, TOP DECK - CONTINUOUS. Julie Raymond's face, zoom out to have a view of her taking a slow walk in the open space on the top deck of the ship, she seems reflective rather than cheerful, despite the fact she's onboard a luxury cruise ship.</div><p><span style="font-size:13px">DISSOLVE TO: INT. OFFICE SPACE, DAYTIME. </span></p></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false"><p><span style="font-size:13px">A GLORIOUS, spacious, glass-walled conference room. One long table. Julie sits at it, absorbed in her work. Her phone rings. She glances at the screen: dr. Reaper. She answers. The camera drifts to a corner of the room, we watch her listen. </span></p><p><span style="font-size:13px">CUT TO: INT. EXPENSIVE RESTAURANT, NIGHT TIME. </span></p><p><span style="font-size:13px">A date between Julie and Llyod. A light conversation between two people who have just met wanting to know more about each other. Llyod is fond of manifestation teachings and he is experimenting with some techniques on several things, one of them is a cruise ship travel.</span></p><p><span style="font-size:13px">"Why?" Julie asked.</span></p><p><span style="font-size:13px">“Honestly? It’s a little embarrassing. When I was about nine, my grandfather sent us a postcard from a cruise ship. It had one line on the back, something like, ‘The water goes on forever and nobody asks you for anything.’</span></p></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false">Lo tuve colgado en la pared de mi dormitorio durante años. Nunca he estado en un lugar donde nadie esperara encontrarme en ninguna parte. Siempre hay un turno, una reparación, una llamada de teléfono. Y un crucero es el único lugar donde lo importante es no hacer nada y dejarse llevar. Creo que solo quiero averiguar si ese sentimiento es real o si es algo que se inventó una postal». Llyod respondió.<br>Julie parece curiosa. «Del 1 al 10, ¿qué tan seguro estás de que vas a poder ir?»<br><br>CORTE A:<br>INT. RESTAURANTE VACÍO. DE NOCHE.<br>La puerta de la cocina se abre de golpe. Marcus (de unos 40 años, con delantal) cruza el local mientras se seca las manos con un paño.<br>«Sabes que cerramos hace veinte minutos, ¿verdad?», Marcus se deja caer en la silla de enfrente.<br>Lloyd no levanta la vista. «Lo sé».<br>Y tú simplemente... estás sentado aquí. A oscuras. Escribiendo.<br> </div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 53px; left: 794px; height: 360px;" contenteditable="false">La verdad es que la iluminación es bastante buena.<br>¿Qué estás escribiendo?<br><div>Solo cosas que quiero que sucedan.</div><div>¿Algo así como una lista de tareas?</div><div>Como una lista de manifestación.</div><div>Marcus parpadea. «¿Una qué, has dicho?»</div><div><div>Cosas que estoy enviando al universo. Intenciones. Declaraciones.</div><div>Ya veo. ¿Y el universo ya te ha respondido?</div><div>Todavía no. Pero me han dicho que la paciencia forma parte del proceso.</div><div>Marcus se inclina, intentando echar un vistazo. «¿Puedo verlo?»</div><div>Lloyd aparta el bloc de notas. «Es algo personal».</div><div>Vivimos juntos durante dos años, Lloyd. Te he visto llorar con un anuncio de gofres.</div><div>Ese gofre era realmente conmovedor.</div><div>Marcus señala el bloc de notas con un gesto. «Venga, solo una cosa.»</div><div>Lloyd suspira e inclina el bloc de notas. Marcus lo lee. Lo lee de nuevo. «Conoce a mi alma gemela». «Eso es... la verdad, es bastante bonito».</div></div></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false">I kept it on my bedroom wall for years. I’ve never once been somewhere where nobody expected me to be anywhere. There’s always a shift, a repair, a phone call. And a cruise is the one place where the whole point is to do nothing and let yourself be carried along. I think I just want to find out if that feeling is real, or if it’s something a postcard made up.” Llyod answered.<br>Julie looks curious. "from 1 to 10, how confident do you think you’ll get to go?”<br><br>CUT TO:<br>INT. EMPTY RESTAURANT. NIGHT TIME.<br>The kitchen door swings open. Marcus (40s, apron) crosses the room, wiping his hands on a towel.<br>"You know we closed twenty minutes ago, right?", Marcus drops into the chair across from him.<br>Lloyd doesn't look up. "I'm aware."<br>And you're just... sitting here. In the dark. Writing.<br></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 53px; left: 794px; height: 360px;" contenteditable="false">The lighting's actually quite good.<br>What are you writing?<br><div>Just things I want to happen.</div><div>Like a to-do list?</div><div>Like a manifestation list.</div><div>Marcus blinks. "A what now?"</div><div><div>Things I'm putting into the universe. Intentions. Declarations.</div><div>Uh-huh. And the universe got back to you yet?</div><div>Not yet. But I'm told patience is part of the process.</div><div>Marcus leans over, trying to peek. "Can I see?"</div><div>Lloyd angles the notepad away. "It's personal."</div><div>We lived together for two years, Lloyd. I've seen you cry at a ommercial for waffles.</div><div>That was a very moving waffle.</div><div>Marcus gestures at the notepad. "Come on. One item."</div><div>Lloyd sighs, tilts the notepad. Marcus reads it. Reads it again. 'Meet my soulmate.' "That's... actually kind of sweet."</div></div></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false"><div>"Gracias." - También es una locura total. No puedes simplemente escribir «conocer a mi alma gemela» en un papel como si fuera la lista de la compra.</div><div>¿Por qué no?</div><div>Porque el universo no es un asistente personal, Lloyd. No puedes simplemente manifestar a una mujer.</div><div>No estoy manifestando «una» mujer. Estoy manifestando a la mujer. A mi mujer.</div><div>Tu mujer.</div>Mi persona.<br>Vale, mira. Necesito hablar contigo de algo.<br>Lloyd deja el bolígrafo sobre la mesa. «Esa nunca es una buena forma de empezar».<br>Quiero que seas mi chef.<br>No sé cocinar.<br>Puedes aprender.<br>¿De verdad puedo?<br><div>Claro. Es simplemente... seguir las instrucciones. Se te da bien seguir instrucciones. Eres la persona que mejor sigue las instrucciones que he conocido en mi vida.</div></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false">Una vez quemé agua.<br class="">No se puede quemar el agua.<br>Encontré una forma.<br>Marcus se frota las sienes. «Lloyd. Voy a perder a mi jefe de cocina». Necesito a alguien en quien pueda confiar. Alguien que venga. Alguien que no se lleve la cubertería.<br>Nunca robaría tus cubiertos.<br>Lo sé. Por eso te lo estoy pidiendo.<br>Pero la verdad es que no sé cocinar en absoluto. Esto no es humildad. Se trata de una limitación objetiva.<br>¿Sabes qué hace un chef?<br>Cocina.<br>No. Un chef dirige. Un chef organiza. Un chef se asegura de que todo vaya según lo previsto y de que nada se venga abajo. Has estado haciendo eso por los demás toda tu vida. Precisamente lo hiciste por mí el mes pasado, cuando organizaste la cena de cumpleaños de mi madre. No cocinaste absolutamente nada y fue perfecto.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false">Thank you.<br><div>Also completely insane. You can't just write "meet soulmate" on a piece of paper like it's a grocery list.</div><div>Why not?</div><div>Because the universe isn't a personal assistant, Lloyd. You can't just manifest a woman.</div><div>I'm not manifesting 'a' woman. I'm manifesting the woman. My woman.</div><div>Your woman.</div>My person.<br>Okay, look. I need to talk to you about something.<br>Lloyd sets the pen down. "That's never a good opener."<br>I want you to be my chef.<br>I don't know how to cook.<br>You can learn.<br>Can I?<br><div>Sure. It's just... following instructions. You're good at instructions. You're the most instruction-following person I've ever met.</div></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false">I burned water once.<br>You can't burn water.<br>I found a way.<br>Marcus rubs his temples. "Lloyd. I'm losing my head chef. I need someone I trust. Someone who'll show up. Someone who won't steal the silverware.|<br>I would never steal your silverware.<br>I know. That's why I'm asking you.<br>But I genuinely cannot cook. This isn't humility. This is a factual limitation.<br>You know what a chef does?<br>Cooks.<br>No. A chef manages. A chef organizes. A chef makes sure everything happens on time and nothing falls apart. You've been doing that for people your whole life. You just did it for me last month when you planned my mother's birthday dinner. You didn't cook a single thing and it was perfect.<br></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 407px; height: 360px;" contenteditable="false"><p class="">Lloyd lo piensa. «Es cierto». Delegué de forma muy eficaz."</p><p>¿Ves? Se te da de maravilla.</p><p>Llyod&nbsp; empieza a toser; le entra un ataque breve e intenso. Marcus lo observa con simpatía.&nbsp;<br>«¿Y si enveneno a alguien?», Llyod comentó, recuperándose de su ataque de tos.</p><p>Entonces nos encargaremos de ello. Para eso están los amigos.</p><p>De verdad, eso es lo más preocupante que me has dicho nunca.</p><p>Piénsalo bien. La oferta es de verdad.</p><p>Se pone de pie, se mete la toalla en el delantal, empieza a caminar hacia la cocina y, luego, se detiene. «Y, Lloyd, ¿cuándo la conocerás?» ¿La alma gemela? Tráela aquí. Cocinaré para los dos. Invita la casa. Además, si estás manifestando cosas... tal vez deberías añadir «aprender a cocinar» a la lista. Buenas noches, Lloyd.»</p></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="true">Buenas noches, Marcus.<br class=""><p>DESVANECIMIENTO.</p></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 43px; left: 407px; height: 360px;" contenteditable="false"><p class="">Lloyd considers this. "That's true. I did delegate very effectively."</p><p>See? You're a natural.</p><p>Llyod&nbsp; starts to cough, it comes in a short, hard fit. Marcus watches sympathetically.&nbsp;<br>"What if I poison someone?" Llyod remarked, recovering from his cough.</p><p>Then we'll deal with it. That's what friends are for.</p><p>That's genuinely the most concerning thing you've ever said to me.</p><p>Sleep on it. The offer's real.</p><p>He stands, tucks the towel into his apron, starts toward the kitchen, then pauses. "And Lloyd, when you meet her? The soulmate? Bring her here. I'll cook for you both. On the house. Also, if you're manifesting things... maybe add learn to cook to the list. Goodnight, Lloyd."</p></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="true">Goodnight, Marcus.<br class=""><p>FADE OUT.</p></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">Mal Día</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 89px; left: 407px; height: 360px;" contenteditable="false">Kevin Rush se despertó a las 7:03 de la mañana con el sabor de la ambición y el aliento de un mapache. Era domingo. Y, lo que era más importante, era el domingo de su cita a ciegas, una cena con Lisa Ries, a quien nunca había conocido. Kevin había planeado pasar el día preparándose con tranquilidad. En vez de eso, se arrastró hasta la cocina, pulsó el botón de la cafetera y solo escuchó un gorgoteo triste y vacío. Se había quedado sin café. Completamente. Ni un grano, ni café molido, ni siquiera uno de esos misteriosos sobres de café instantáneo que sabían a ceras de color marrón. Solo había un filtro solitario en la cafetera, como un pequeño fantasma. «Mal presagio», susurró Kevin. Decidido a salvar el día, Kevin optó por darse el capricho de un sofisticado café con leche en el centro. Paró un taxi, un coche amarillo brillante conducido por un hombre llamado Stan.<p>APERTURA:</p><p>EXT. CENTRO DE LA CIUDAD - MAÑANA</p><p>Un TAXI amarillo se abre paso entre el tráfico.</p></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="true"> Dentro, KEVIN va sentado en el asiento trasero. Mira su reloj. Luego, el portavasos vacío que está a su lado. Luego, vuelve a mirar el reloj.<p>KEVIN (voz en off)</p><p>«Hay días en los que simplemente necesitas darte un capricho».</p>El taxi esquiva un camión de reparto.<p>KEVIN (VOZ EN OFF)</p><div>"Nada descabellado. Nada irresponsable. Solo un café con leche especial. Quizá uno de esos pastelitos que ponen detrás de una vitrina como si fueran las Joyas de la Corona».<br> Al volante está STAN, de unos cincuenta años, con un bigote enorme y la seguridad de un hombre que nunca se ha sentido avergonzado en público. Está cantando ópera. A todo pulmón. De forma espantosa.</div><p>STAN</p><div>(cantando) ¡OOOOOOOOOH!</div></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">Bad Day</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 89px; left: 407px; height: 360px;" contenteditable="false">Kevin Rush woke at 7:03 a.m. with the taste of ambition and the breath of a raccoon. It was Sunday. More importantly, it was the Sunday of his blind date, a dinner with Lisa Ries, whom he had never met before. Kevin had planned to spend the day calmly preparing. Instead, he shuffled into the kitchen, pressed the coffee maker’s button, and heard only a sad, hollow gurgle. He had run out of coffee. Completely. Not a bean, not a ground, not even one of those mysterious instant packets that tasted like brown crayons. Only a lonely filter sat in the machine like a tiny ghost. “Bad omen,” Kevin whispered. Determined to salvage the day, Kevin decided to treat himself to a fancy latte downtown. He hailed a taxi, a bright yellow car driven by a man named Stan.<p>FADE IN:</p><p>EXT. DOWNTOWN - MORNING</p><p>A yellow TAXI cuts through traffic. Inside, KEVIN sits in the back seat. He checks his watch. Then the empty cup holder beside him. Then the watch again.</p></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="true"><p>KEVIN (V.O.)</p><p>"There are days when you just need to treat yourself."</p>The taxi swerves around a delivery truck.<p>KEVIN (V.O.)</p><div>"Nothing crazy. Nothing irresponsible. Just a fancy latte. Maybe one of those little pastries they put behind glass like it's the Crown Jewels."<br> Behind the wheel is STAN, fifties, enormous mustache, the confidence of a man who has never once been embarrassed in public. He is singing opera. Loudly. Painfully.</div><p>STAN</p><div>(singing) OOOOOOOOH!</div></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 51px; left: 407px; height: 360px;" contenteditable="false">Kevin mira fijamente la nuca de Stan. «¿Tú, eh... cantas profesionalmente?»<br> Stan da una nota que parece asustar a una paloma posada en un cable del teléfono. «No. Soy taxista».<br>Kevin asiente. «Claro, por supuesto». <br>El taxi gira hacia una avenida muy transitada que bordea el DISTRITO FINANCIERO. Stan se prepara para otro ataque operístico. Y entonces... UN HOMBRE CON MÁSCARA DE PAYASO cruza la calle corriendo. Detrás de él: OTROS TRES PAYASOS. Llevan sacos negros abultados. Uno de ellos lleva unas gafas de sol extragrandes. Otro lleva un plátano. Kevin se hunde lentamente en su asiento.<p></p>«Stan».<br>«¿Qué?»<br>«¿Es un atraco a un banco?» <p>Stan mira a través del parabrisas. Los payasos desaparecen al doblar una esquina. A Stan se le iluminan los ojos. «¡Parece que sí!» Pisa el acelerador.</p></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 45px; left: 786px; height: 360px;" contenteditable="false">«¿Por qué estás acelerando?»<br>«¡Quiero verlo!»<br>«¡Eres taxista!»<br>        «¡Exacto! Siempre estoy en medio del tráfico. ¡Es la primera cosa interesante que me pasa en once años!»<br><p>Más adelante, un COCHE DE POLICÍA SE DESVÍA DE REPENTE al cruzar el cruce. Stan pisa el freno a fondo. LOS NEUMÁTICOS CHILLAN. Las manos de Kevin, sin su café con leche, se disparan hacia delante. El taxi pasa a escasos centímetros del coche de policía. No lo evita—<strong>CRUNCH.&nbsp;</strong>Un CAMIÓN DE HELADOS aparcado. Silencio. Luego... &nbsp;<strong>¡DÍN-DÍN-DÍN-DÍN-DÍN!&nbsp;</strong>Los altavoces del camión de helados cobran vida de repente.&nbsp;<em>"LA COMADREJA SE VA DE PINGA."&nbsp;</em>A todo volumen. Stan mira a través del parabrisas. Kevin mira fijamente a Stan. Stan mira fijamente al camión de los helados.&nbsp;</p>«Venga ya».<br></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 51px; left: 407px; height: 360px;" contenteditable="false">Kevin stares at the back of Stan's head. "You, uh... sing professionally?"<br> Stan hits a note that seems to frighten a pigeon off a telephone wire. "No. I drive a taxi."<br>Kevin nods. "Right, naturally." <br>The taxi turns onto a busy avenue bordering the FINANCIAL DISTRICT. Stan prepares for another operatic assault. And then— A MAN IN A CLOWN MASK sprints across the street. Behind him: THREE MORE CLOWNS. They're carrying bulging black sacks. One of them is wearing an oversized pair of sunglasses. Another is carrying a banana. Kevin slowly lowers himself in his seat.<p></p>"Stan."<br>"What?"<br>"Is that a bank robbery?" <p>Stan looks through the windshield. The clowns disappear around a corner. Stan's eyes light up. "Looks like it!" He hits the accelerator.</p></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 45px; left: 786px; height: 360px;" contenteditable="false">"Why are you speeding up?!"<br>"I wanna see!"<br>"You're a taxi driver!"<br>        "Exactly! I'm always in traffic. This is the first interesting thing that's happened to me in eleven years!"<br><p>Up ahead, a POLICE CAR suddenly SWERVES across the intersection. Stan slams the brakes. TIRES SCREECH. Kevin's latte-less hands shoot forward. The taxi misses the police car by inches. It does not miss—<strong>CRUNCH.&nbsp;</strong>A parked ICE CREAM TRUCK. Silence. Then—&nbsp;<strong>DING-DING-DING-DING-DING!&nbsp;</strong>The ice cream truck's speakers explode to life.&nbsp;<em>"POP GOES THE WEASEL."&nbsp;</em>At full volume. Stan stares through the windshield. Kevin stares at Stan. Stan stares at the ice cream truck.&nbsp;</p>"Oh, come on."<br></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false"><p>La música continúa.&nbsp;<em>«POP GOES THE WEASEL».&nbsp;</em>Al otro lado de la calle, los cuatro payasos han dejado de correr. Ahora se encuentran frente a una fila de AGENTES DE POLICÍA. Con las armas desenfundadas, los payasos levantan las manos. Nadie se mueve. Y, durante todo el&nbsp;impasse:&nbsp;<em>«POP GOES THE WEASEL».&nbsp;</em>Un payaso asiente lentamente al compás de la música. Otro empieza a golpetear con el pie. Kevin observa con incredulidad.</p><p>KEVIN<br>¿Están... disfrutando de esto?</p><p>STAN<br>La buena música es buena música.</p><p>La VENDEDORA DE HELADOS, una mujer furiosa de unos sesenta años, se dirige a toda prisa hacia el taxi.</p><p>VENDEDORA DE HELADOS<br>¡Me has dado a mi furgoneta!</p></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false"><p>Stan abre la puerta. «Que nadie se asuste».</p><p>Kevin mira a los agentes de policía armados, a los cuatro payasos detenidos y al camión de helados destrozado.&nbsp;«Creo que ya hemos pasado ese punto».&nbsp;</p><p>Stan sale.&nbsp;«Datos del seguro. Permiso de conducir. Documentación del vehículo».</p><p>El vendedor señala el camión abollado.&nbsp;«¡Has destrozado el parachoques!»</p><p>«Técnicamente, el parachoques sigue ahí».</p><p>«¡ESTÁ A PUNTO DE CAERSE!»</p><p>Stan lo examina.&nbsp;«Vale. Emocionalmente, sigue estando ahí. El vendedor lo mira con mala cara. Detrás de ellos, la multitud ha ido creciendo. Nadie sabe exactamente qué ha pasado. A nadie le importa. La gente está sacando sus teléfonos. La policía está gritando. Están esposando a los payasos. El camión de los helados sigue sonando.&nbsp;<em>"LA COMADREJA SALTA."</em></p></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false"><p>The music continues.&nbsp;<em>"POP GOES THE WEASEL."&nbsp;</em>Across the street, the four clowns have stopped running. They are now facing a line of POLICE OFFICERS. Guns drawn. The clowns raise their hands. Nobody moves. And over the entire standoff:&nbsp;<em>"POP GOES THE WEASEL."&nbsp;</em>One clown slowly nods to the rhythm. Another starts tapping his foot. Kevin watches in disbelief.</p><p>KEVIN<br>Are they... enjoying this?</p><p>STAN<br>Good music is good music.</p><p>The ICE CREAM VENDOR, a furious woman in her sixties, storms toward the taxi.</p><p>ICE CREAM VENDOR<br>You hit my truck!</p></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false"><p>Stan opens his door. "Nobody panic."</p><p>Kevin looks at the armed police officers, four detained clowns, and the wrecked ice cream truck.&nbsp;"I think we're way past that."&nbsp;</p><p>Stan steps out.&nbsp;"Insurance information. License. Registration."</p><p>The vendor points at the dented truck.&nbsp;"You destroyed the bumper!"</p><p>"Technically, the bumper is still there."</p><p>"IT'S HANGING OFF!"</p><p>Stan examines it.&nbsp;"Okay. It's emotionally still there." The vendor glares at him. Behind them, the crowd has grown. Nobody knows exactly what happened. Nobody cares. People are taking out their phones. The police are shouting. The clowns are being handcuffed. The ice cream truck is still playing.&nbsp;<em>"POP GOES THE WEASEL."</em></p></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 39px; left: 789px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false"><p class="">De repente, el vendedor empieza a repartir conos de helado que se están derritiendo entre los espectadores.«¡COGEDLOS! ¡NO LOS VOY A VOLVER A METER EN EL CONGELADOR!» La gente aplaude. Stan mira a su alrededor. Parece extrañamente orgulloso.</p><p>STAN: ¿Lo ves?</p><p>Kevin se baja del taxi.«¿Ver qué?»<br> Stan señala el caos con un gesto.«El centro».<br> Kevin mira los restos del accidente. Luego, a los payasos. Luego, a la policía. Luego, al cucurucho de helado que alguien acaba de meterle en la mano. Da un bocado.«Esta no es la cafetería.»</p><p>Stan sonríe. «No».</p><p>La música sigue sonando.<br><br>CORTE A NEGRO.</p>El resto del día transcurrió como un montaje surrealista. Por fin llegó a casa, se cambió de ropa y llamó a otro taxi.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 39px; left: 786px; height: 360px;" contenteditable="false"><p class="">La conductora era una mujer prudente que iba exactamente a la velocidad máxima permitida. Estaban a dos manzanas del restaurante cuando un autobús urbano, decorado como un taco gigante para un festival, tuvo un pequeño percance con una boca de incendios. Un géiser entró en erupción, empapando su coche y haciendo que el motor se calara temporalmente. «Creo», dijo la conductora con calma, mientras el agua goteaba del espejo retrovisor, «que debería ir andando».</p><div></div><div>Así que Kevin lo hizo, y sus zapatos relucientes hacían un ruido характерный para el barro a cada paso. Llegó a Il Ristorante con el aspecto de un hombre que había luchado contra la naturaleza y había perdido. Se alisó el pelo, respiró hondo y lo condujeron a una mesa en un rincón, donde había una mujer sentada, sonriendo mientras miraba la carta. Iba impecablemente vestida, estaba seca y bebía una copa de vino con un aire de serena calma. Kevin sintió que todo aquel día absurdo se le acumulaba dentro. Ella levantó la mirada, con una sonrisa cálida y curiosa. «Hola», dijo Kevin, tendiendo una mano ligeramente húmeda. «Soy Kevin. Tú debes de ser Lisa». Siento estar… bueno, ha sido un domingo muy largo.»</div></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 39px; left: 789px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;" contenteditable="false"><p class="">The vendor suddenly starts handing out melting ice cream cones to the spectators."TAKE 'EM! I'M NOT PUTTING THEM BACK IN THE FREEZER!" People cheer. Stan looks around. He seems strangely proud.</p><p>STAN:See?</p><p>Kevin gets out of the taxi."See what?"<br> Stan gestures toward the chaos."Downtown."<br> Kevin looks at the wreckage. Then at the clowns. Then at the police. Then at the ice cream cone someone has just shoved into his hand. He takes a bite."This isn't the coffee shop."</p><p>Stan smiles."No."</p><p>The music keeps playing.<br><br>CUT TO BLACK.</p></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 40px; left: 785px; height: 360px;" contenteditable="false"><p class="">The rest of the day unfolded in a surreal montage. He finally made it home, changed outfit, and called for a new taxi. This driver was a cautious woman who drove precisely at the speed limit. They were two blocks from the restaurant when a city bus, decorated like a giant taco for a festival, had a minor disagreement with a fire hydrant. A geyser erupted, drenching their car and temporarily stalling the engine. “I think,” the driver said calmly, as water dripped from the rearview mirror, “you should walk.”</p><div></div><div>So Kevin did, his polished shoes making squelching sounds with every step. He arrived at Il Ristorante looking like a man who had fought nature and lost. He smoothed his hair, took a deep breath, and was led to a corner table where a woman sat, smiling over a menu. She was impeccably dressed, dry, and sipping a glass of wine with an air of serene calm. Kevin felt the entire absurd day welling up inside him.She looked up, her smile warm and curious. “Hi,” Kevin extending a slightly damp hand. “I’m Kevin. You must be Lisa. Sorry I’m… well, it’s been a very long Sunday.”</div></div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 39px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 56px; left: 407px; height: 360px;" contenteditable="false"><p>Platforms / Models used:<br>DeepSeek,<br>Claude.ai (Llyod's date question answer),<br>Perplexity.ai,<br>Gemini,<br>ChatGPT,<br>Tusk Central AI (new.tusksearch.com/ai)</p><br><div>Spanish Translation:<br>https://laratranslate.com</div></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"></div>`;

vte[vte.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 39px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 56px; left: 407px; height: 360px;" contenteditable="false"><p>Platforms / Models used:<br>DeepSeek,<br>Claude.ai (Llyod's date question answer),<br>Perplexity.ai,<br>Gemini,<br>ChatGPT,<br>Tusk Central AI (new.tusksearch.com/ai)</p><br><div>Spanish Translation:<br>https://laratranslate.com</div></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"></div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

export function openBoard(){
    jve.dbF.qr.initBook(dbset,drabindex);
}
