var vt = [];
var vte = [];
export var dbset = [];

var dbbtn = `<div id="dbbutton" class="textshirt dbbutton" style="top: 91.3769%; left: 95.4652%; width: 36px; height: 36px;"><div id="dbbutton2" class="dbbutton textshirt circleshirt" style="height: 36px; width: 36px; top: 91.3769%; left: 95.4652%; background-color: rgb(255, 255, 255); border-color: rgb(255, 255, 255); color: rgb(255, 255, 255);"></div><div id="dbbutton3" class="dbbutton textshirt circleshirt" style="height: 22px; width: 22px; top: 92.4896%; left: 96.0907%;"></div></div>`;

//to adjust
export const dbtitle = 'directorscut';
const defaultspeed = 25;
const transws = ' wspeed_10';
const drabindex = 'directorscut';

const bimgpath = storyline.jsonUrl+'./drawboard/bimg/openbook-581128.jpg';
var dbbg =`<div id="dbbackg" class="textshirt imageshirt" style="left: -14px; top: -72px; width: 1280px; height: 853px;"><img src="`+bimgpath+`"></div>`;
dbbg += '<style>.textshirt{color:#000;font-family:EBGaramond;}</style>';



vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">Bergman</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;"><br><b>El soltero</b><br><br>  Introducción:<br> Estamos observando el entorno de un apartamento: una colchoneta de yoga, algunas plantas bonsái y un pequeño rincón de trabajo con una computadora, un cuaderno y un bolígrafo. Cosas de lo más normal.<br><br> Kevin Rush, un hombre común, neurótico y centrado en su carrera que acaba de entrar en la cuarentena, se resiste a levantarse de la cama, aunque ya está despierto. Kevin es lo que podrías considerar un macho alfa autosuficiente. Agitado e irritado, trata de identificar qué le falta en la vida, ya sea una pareja sentimental o algo completamente distinto. Como nunca ha tenido una relación de verdad, ahora se pregunta si realmente es necesaria o si ya dejó pasar su oportunidad. Pero, ¿qué significa eso en realidad?</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Este ha sido un tema recurrente para Kevin a altas horas de la noche, mientras navega en internet en busca de los “métodos” adecuados para experimentar. A menudo se distrae con cosas inusuales que encuentra en la red, lo que lo lleva a sumergirse en un profundo laberinto de temas que van desde las novias por correspondencia hasta las relaciones románticas con inteligencias artificiales, pasando por las citas internacionales, el estudio de culturas distintas a la suya, la canalización de entidades multidimensionales, los supuestos secuestros por fenómenos aéreos no identificados (UAP), la naturaleza de la creatividad, la metafísica de la creación e incluso Dios mismo. Es un momento solitario, pero emocionante para él.<br><br> No es muy sociable y rara vez interactúa con sus amigos, quienes, al parecer, ya han formado sus propias familias y están ocupados con sus propias vidas, dejándolo solo para decidir si seguir su ejemplo o no. <br><br><b>La soltera</b><br>   Julie Raymond es lo que uno consideraría una mujer promedio, neurótica y centrada en su carrera, de unos treinta y tantos años.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">Bergman</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;"><br><b>The Bachelor</b><br><br>  Intro: <br>We are looking at the surroundings of an apartment—a yoga mat, a few bonsai plants, and a small workspace corner with a computer, a notebook, and a pen. Just regular stuff. <br><br>Kevin Rush—an average, neurotic, career-focused male just stepping into his forties—is reluctant to get out of bed, though he is already awake. Kevin is what you might perceive as a self-sufficient alpha male. Agitated and irritated, he is trying to identify what he lacks in life—whether it's a female life partner or something else entirely. Having never been in a real relationship, he now wonders if one is actually necessary or if he has already missed his chance. But what does that even mean?</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">This has been a frequent late-night topic for Kevin, browsing online for the suitable 'methods' to experiment - often sidetracking to unusual stuff found in the internet, leading to a deep rabbit hole, ranging from mailbride to romantic relationship with AIs to dating beyond borders, a study into other cultures other than his own, to channeling multidimensional entities, to UAP abduction to the nature of creativity to the metaphysics of creation and even to God Himself - It's a solitary but exciting time for him.<br><br> He isn't very sociable and rarely interacts with friends - all of whom seem to have started their own families and are busy with their own lives - leaving him alone to decide whether to follow suit, or not. <br><br><b>The Bachelorette</b><br><br>   Julie Raymond is what you would perceived as an average, neurotic, career focused female in her mid-thirties.</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Está explorando sus opciones para atraer a una pareja, probando de todo, desde coaching para citas y técnicas de manifestación hasta salir a la vida social para conocer, por casualidad, a posibles nuevas parejas.<br>  Antes no tenía problemas para entablar relaciones, pero no ha surgido nada nuevo desde su última ruptura hace diez meses, la cual fue un acontecimiento muy importante para ella.  <br>Entre sus amistades, Julie es conocida por ser una persona muy activa y cálida. Aunque la mayoría ya ha formado su propia familia, ella suele intercambiar opiniones sobre el tema de formar una familia con las pocas que aún no lo han hecho.  <br><br>El grupo de amigas se reúne para almorzar. Lisa Ries, psicóloga clínica, inicia la conversación presentándoles inMatch Odyssey, una agencia de citas que se basa en un nuevo algoritmo y una nueva técnica. Esta agencia requiere que sus clientes realicen numerosos tests de autoevaluación de personalidad, en los que deben expresar e identificar sus valores internos y su orientación hacia el futuro como información de entrada para el sistema.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Lisa está muy entusiasmada con que Julie encuentre su próxima relación porque quiere que su amiga sea feliz y cree que realmente se lo merece. Sin embargo, bajo su optimismo profesional y la esperanza sincera de una amiga, reprimía una pregunta que la atormentaba: ¿pueden las técnicas de vanguardia de la agencia crear conexiones humanas, o simplemente están proyectando sus vacíos más profundos en una caja negra, confundiendo un algoritmo con el destino?<br><br>  Esa pregunta no se le borra del rostro. Se instala allí. En silencio. Como la escarcha que se forma en el vidrio.  La cámara no se mueve. Se mantiene fija en Lisa en un PRIMER PLANO cerrado y agobiante. Del tipo que elimina el contexto. Sin habitación. Sin amigos. Sin almuerzo. Solo su rostro. Sus ojos. El más leve temblor en la comisura de sus labios es la única señal de que algo se ha quebrado bajo la superficie.  Las voces de sus amigas siguen sonando. Riendo. Masticando. Viviendo. Pero el sonido se va apagando. Se atenúa. Como si se oyera a través de una pared, a través del agua, a través de años de una compostura entrenada que poco a poco deja de cumplir su función.  SILENCIO. </div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">She is exploring her options on how to attract a significant other, trying everything from dating coaching and manifestation techniques to going out into the social scene to meet potential new partners by chance. <br> She previously had no problem building relationships, but nothing new has come up since her last breakup ten months ago, which was a major event for her.  <br>Julie is known as a very active, warm person among her friends. While most have already settled down with their own families, she frequently exchanges thoughts on the topic of starting a family with the few who haven't yet. <br><br> The group of friends are gathering for lunch, Lisa Ries who is a clinical psychologist starts the conversation by introducing the women to inMatch Odyssey, a dating agency based on a new algorithm and technique, requiring its clients to take plenty of self-assessment personality test, articulating and identifying their inner values and future orientation as an input to the system.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;"> Lisa is very vibrant about Julie finding her next relationship because she wants her friend to be happy and believes she truly deserves it, but beneath her professional optimism and  a sincere friend's hope, she suppressed a haunting question—can the agency's state of the art techniques engineer human connection, or are they all merely projecting their deepest voids into a black box, mistaking an algorithm for destiny?"  <br><br> That question does not leave her face. It settles there. Quietly. Like frost forming on glass.  The camera does not move. It holds on Lisa in a tight, suffocating CLOSE-UP. The kind that strips away context. No room. No friends. No lunch. Just her face. Her eyes. The faintest tremor at the corner of her mouth—the only evidence that something has cracked beneath the surface.  The voices of her friends continue. Laughing. Chewing. Living. But the sound thins. Dulls. As though heard through a wall, through water, through years of trained composure slowly failing its purpose.  <br><br>SILENCE. </div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 401px; height: 360px;">No es el silencio cinematográfico. No es la pausa elegante que precede a un crescendo. Silencio de verdad. Ese tipo de silencio que solo existe dentro de una persona, cuando todos los ruidos externos se convierten en mero adorno y la voz interior se vuelve insoportablemente fuerte.  La cámara se mantiene fija.<br class=""><br> Lisa parpadea. Una vez. Lentamente. El tipo de parpadeo que no es un reflejo, sino una puerta que se cierra.  Entonces, un CAMBIO.  Un CORTE brusco a un PLANO GENERAL.  La mesa. Los amigos. La comida. La luz del día que entra por la ventana con una indiferencia cruel. Todo está nítido. Todo está enfocado. El mundo no se ha detenido. Al mundo le es indiferente su pregunta. La lechuga está crujiente. El agua refleja la luz. Alguien pasa el pan.  Lisa estira la mano para tomar su vaso. Su mano está firme. Vuelve a sonreír. Una sonrisa ensayada. Profesional. Apropiada.  Ella bebe.  La cámara observa. Inmóvil. La toma es simétrica. La composición está equilibrada. Todo está en su sitio.  Y, sin embargo, nada queda resuelto. No llega ninguna respuesta. No llegará ninguna respuesta. El encuadre simplemente se detiene en un grupo de personas que comen juntas a plena luz del día.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 36px; left: 786px; height: 360px;">Cada una de ellas lleva consigo un mundo interior insondable en una tarde cualquiera, y la distancia entre ellas es a la vez exacta e inconmensurable.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Not cinematic silence. Not the elegant pause before a crescendo. Real silence. The kind that exists only inside a person when every external noise becomes decoration and the interior voice grows unbearably loud.  The camera holds.<br><br> Lisa blinks. Once. Slowly. The kind of blink that is not a reflex but a door closing. Then—a SHIFT.  A hard CUT to a WIDE SHOT.  The table. The friends. The food. The daylight pouring through the window with cruel indifference. Everything is sharp. Everything is in focus. The world has not stopped. The world does not care about her question. The lettuce is crisp. The water catches light. Someone passes the bread.  Lisa reaches for her glass. Her hand is steady. Her smile returns. Practiced. Professional. Adequate.  She drinks.  The camera watches. Motionless. The shot is symmetrical. The composition is balanced. Everything is in its right place.  And yet nothing is resolved. No answer comes. No answer will come. The frame simply holds—on a group of people eating together in broad daylight, each one carrying an unfathomable interior into an ordinary afternoon, the distance between them exact and immeasurable.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;"></div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">Kubrick</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 90px; left: 407px; height: 360px;">El interés por estar en una relación “romántica” es un error por definición, al menos para mí. Una relación romántica no va a llenar lo que creo que me falta en mi propia vida. No es que me falte una especie de locura impulsiva, una experiencia sensorial y emocional, algo que se “eleva” al tener una barrera entre uno y el objetivo. Creo que puedo tener eso con bastante facilidad sin recurrir a algo tradicionalmente mundano y convertirlo en algo parecido a las sensaciones que se obtienen al jugar en las máquinas tragamonedas. ¿Por qué me interesaría buscar algo que ya está... aquí? <br class=""><br>   El amor romántico como motivo para contraer matrimonio es un concepto nuevo en la civilización, que surgió entre finales del siglo XIX y principios del siglo XX. En ese periodo, las relaciones íntimas dejaron de estar tan restringidas por las figuras de autoridad, y el feminismo dio lugar a un nuevo tipo de relación entre hombres y mujeres, lo que, a su vez, provocó un aumento en la tasa de divorcios. Los estudios han demostrado que los matrimonios arreglados tienen tasas de satisfacción más altas que los matrimonios por amor, entonces, ¿por qué enamorarse y luego casarse?</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 33px; left: 786px; height: 360px;"> Una especie de locura impulsiva y una experiencia sensorial emocional, intensificada por la existencia de una barrera hacia un objetivo, parecían no sugerir tal cosa en primer lugar. ¿Por qué involucrarse en... “algo” solo porque una voz en particular lo aconseja, cuando esa voz no respalda la totalidad de la situación en la que te encuentras y que te hizo pensar en... involucrarte en cualquier cosa? O, para usar lo que sugirió una IA: “¿Por qué adoptar una solución de una voz que no ve el ecosistema que generó tu problema?” O, como alternativa: “Es contraproducente aceptar una solución táctica de una fuente que no comprende la complejidad estratégica de tu entorno actual”.   <br>Mira fijamente las líneas tachadas, el grafito manchado, las frases que suenan como una máquina descompuesta. Deja escapar un suspiro lento.  <br><br> “Nunca supe cómo decir las cosas bien”. <br><br> Con un suspiro silencioso, Kevin cierra su diario, cuyas páginas están repletas de los pensamientos del día. La tinta se siente pesada, un peso tangible en sus dedos.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">Kubrick</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;">The interest to be in a 'romantic' relationship is an error by definition, at least to me, a romantic relationship wont fulfill what i think is missing in my own life. i'm not missing a kind of madness of the impulse, an emotional sensory experience - something that is 'elevated' by having a barrier to a target, i think i can have this quite easily without utilizing something traditionally mundane and converting it into something that are similar to the sensations that we get by playing slot machines. why would i be interested in reaching out for something that is already... here. <br><br>  Romantic love as the reason for marriage is a new concept in civilization starting in between the late 19th century and early 20th century where intimate relationship became less restricted by any figure of authority and feminism creates a new type of man-women relationship and with it brought a rise in divorce rate. Studies showed that arranged marriages has a higher rates of satisfaction than marriages for love, so why be in love and then get into marriage?</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">a kind of madness of the impulse and an emotional sensory experience elevated by having a barrier to a target seemed to not suggests such a thing in the first place. Why go into... 'something' because it is advised by a particular voice that doesn't endorsed the whole situation that you're in that made you think about... going into anything ? or to use what an AI suggested, "Why adopt a remedy from a voice blind to the ecosystem that created your pain?" or the alternative ""It is counterproductive to accept a tactical solution from a source that fails to grasp the strategic complexity of your current environment."  <br><br>He stares at the crossed-out lines, the smudged graphite, the sentences that read like a broken machine. He lets out a slow breath. <br><br> "Never did know how to say things right." <br><br> With a quiet sigh, Kevin closes his journal, its pages filled with the day's thoughts. The ink feels heavy, a tangible weight on his fingers.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Deja el libro sobre el escritorio; la encuadernación de cuero se siente fría contra su palma. Afuera, la noche se va colando y cubre la ciudad con su sombra. Se levanta de su silla, con la mirada atraída hacia la ventana. El cielo nocturno se despliega allá arriba, una inmensa extensión de oscuridad salpicada de estrellas. Una estrella fugaz surca el cielo, un fugaz destello de belleza cósmica.  <br><br>Sale al exterior y el aire fresco lo envuelve. La luna, una delgada media luna, cuelga baja e ilumina el suelo que hay debajo. Se queda allí, con su aliento formando nubecillas en el frío, mirando hacia arriba. El universo se alza por encima, como un tapiz brillante de infinitas posibilidades. Resulta impresionante y nos hace sentir humildes pensar que existe un número incalculable de galaxias más allá de su alcance.  Mientras contempla la inmensidad, se siente pequeño, una mota en el gran esquema de las cosas. Sin embargo, en ese momento, encuentra consuelo en la grandeza del universo. No está solo en esta inmensidad, no puede estarlo. Las estrellas son testigos de su existencia, compañeras silenciosas en la oscuridad eterna.  No parpadea. No se mueve. Simplemente mira hacia arriba.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">EXT. CIELO NOCTURNO – CONTINUACIÓN<br>  La cámara permanece fija en el rostro de Kevin durante un largo momento.  La perspectiva es plana, simétrica, perfectamente centrada: un retrato de un hombre suspendido en el tiempo.  Lentamente. Con una lentitud casi imperceptible. La cámara empieza a retroceder. Se trata de un movimiento de cámara sobre rieles, constante y mecánico. Sin prisa. Inexorable. El encuadre se amplía. Kevin se hace más pequeño dentro de la composición.  La cámara sigue retrocediendo.  Todo lo que lo rodea es reemplazado por un vacío absoluto, completamente negro.  Solo queda Kevin. Un monolito solitario e iluminado de carne y hueso, empequeñecido por un océano de oscuridad y por los brillantes puntos de luz estrellada que lo rodean. La simetría se vuelve absoluta. Una alineación perfecta.  No hay música. El retroceso no se detiene. No se corta. Simplemente se mantiene, dejando que la inmensa escala del vacío se trague el encuadre, hasta que Kevin no sea más que un punto azul pálido. Un solo grano de arena suspendido en un desierto negro e indiferente.<br>  MANTENER EL PLANO EN EL VACÍO.<br>   [FIN DEL GUIÓN]</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">He sets the book down on the desk, the leather binding cold against his palm. Outside, the night creeps in, shadowing the city. He rises from his chair, his eyes drawn to the window. The night sky unfolds above, a vast expanse of darkness peppered with stars. A shooting star streaks across the canvas, a fleeting glimpse of cosmic beauty. <br><br> He steps outside, the cool air washing over him. The moon, a crescent sliver, hangs low, illuminating the ground below. He stands there, his breath forming clouds in the chill, gazing upwards. The universe looms above, a brilliant tapestry of infinite possibilities. It's awe-inspiring, humbling to think a countless number of galaxies exist beyond his reach.  As he contemplates the immensity, he feels small, a speck in the grand scheme of things. Yet, in that moment, he finds solace in the universe's grandeur. He is not alone in this vastness, can't be. The stars are witnesses to his existence, silent companions in the eternal darkness. He doesn't blink. He doesn't move. He simply stares upward.  </div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">EXT. NIGHT SKY – CONTINUOUS <br><br>The camera remains fixed on Kevin’s face for a prolonged moment.  The perspective is flat, symmetrical, perfectly centered—a portrait of a man suspended in time. Slowly. Imperceptibly slowly. The camera begins to pull backward. It is a steady, mechanical dolly track. Unhurried. Inexorable. The frame expands. Kevin shrinks within the composition.  The camera continues to retreat.  everything in  his surrounding is replaced by an absolute, pitch-black void.  Only Kevin remains. A solitary, illuminated monolith of flesh and bone, dwarfed by an ocean of darkness and the brilliant, starlit points of light surrounding him. The symmetry becomes absolute. Perfect alignment.  There is no music. The pull-back does not stop. It does not cut. It merely holds, allowing the immense scale of the void to swallow the frame, until Kevin is nothing more than a pale blue dot. A single grain of sand suspended in a black, indifferent desert. <br> HOLD ON THE VOID. <br> [END SCRIPT]</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">Ozu</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 96px; left: 407px; height: 360px;">Julie está haciendo sus extensas pruebas de personalidad, que van desde parecer muy científicas hasta francamente tontas. Por cierto, es de Slytherin, no de Gryffindor, lo cual no le dice mucho sobre qué tan altas o bajas deberían ser sus expectativas al probar esta empresa de citas, InMatch Odyssey. <br><br> Después de su prueba, la guían a un pequeño espacio que parece una sala de karaoke. Se sienta en un sofá grande y cómodo para charlar con una amiga IA. <br><i>“Hola, Julie. Me llamo Kathryn. ¿Sabías que, originalmente, la idea del matrimonio era transferir la riqueza de las figuras patriarcales a sus verdaderos hijos biológicos? Esta institución ya tiene 5000 años”</i>, comenzó la IA con entusiasmo. <br><i> “No... no lo sabía”</i>, dijo, un poco sorprendida y también divertida por la apariencia de su nueva amiga.<br><i>“¿Qué dice tu familia sobre cómo debería ser tu pareja de vida?”</i>, pregunta Kathryn con curiosidad.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;"><i>“Ah, y... si logramos ayudarte a encontrar la pareja perfecta, ¿vas a darnos el mérito a nosotros o también has hecho algunos intentos antes?”</i> La expresión de Kathryn se vuelve aún más curiosa. <br> La entrevista forma parte de la prueba de personalidad y te analiza de manera integral: desde aspectos de la voz —velocidad y fluidez del habla, tono, volumen y variación vocal— hasta el contacto visual y la expresividad facial, el tiempo de latencia antes de responder, la actitud defensiva, la inconsistencia o el exceso de control, la postura, la inquietud, los patrones de gestos y la forma en que la persona maneja la ambigüedad, los desafíos o la presión, entre otros aspectos.   La prueba escrita de Julie ya la había ubicado en varios modelos de personalidad diferentes, como la sociónica, el modelo HEXACO, los estilos de apego, el MBTI, el locus de control interno-externo, el modelo PEN de Eysenck, el 16 PF, la tríada oscura, el modelo de temperamento de Cloninger y las escalas clínicas al estilo del MMPI. Pero este siguiente paso no es menos importante. <br> La entrevista de Julie se prolonga. Los minutos se suceden unos a otros como el suave zumbido de la luz ambiental en la habitación.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">Ozu</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 96px; left: 407px; height: 360px;">Julie is taking her extensive personality tests, it ranges from looking very scientifical to downright silly, she is a slytherin by the way not a gryffindor, which doesnt quite tell her about how  high or low her expectation level should be for trying out this InMatch Odyssey dating company. <br><br> After her test she is then guided go to a small quarter that looks like a karaoke room. she sat down on a big comfortable couch to have a chat with an AI friend, <br><i>"Hi Julie, my name is Kathryn, so do you know that the idea of marriage is originally to transfer wealth from patriarchal figures to his true biological children? the institution is already 5000 years old?"</i> the AI vibrantly started the talk. <br><i>"No... i didnt know that"</i>, slightly surprised and also amused by the appearance of her new friend. <br><i>"What does your family say about how your life partner should be like?"</i> Kathryn sounds curious.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;"><i>"Oh and... if we are able to help you find a perfect match, are you going to attribute that to us or have you done some previous efforts as well?"</i> Kathryn's face gets even more curious.  <br><br>The interview is part of the personality test, it analyzes you in a holistic way from voice - speech rate and fluency, pitch, volume, and vocal variation - to eye contact and facial expressiveness to latency before answering, to defensiveness, inconsistency or overcontrol, to posture, restlessness, gesture patterns to how the person handles ambiguity, challenge or pressure, things like that.   Julie's written test already mapped her onto several different personality modelling such as socionics, HEXACO, attachment styles, MBTI, internal-external locust of control, Eysenck’s PEN model, 16 PF, Dark Triad, Cloninger’s temperament and MMPI-style clinical scales. but this next step isn't anything less important. <br><br> Julie's interview stretches on. Minutes fold into each other like the soft hum of ambient light in the room.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">INT. SALA DE KARAOKE – CONTINUACIÓN<br><br>  TOMA A NIVEL DEL TATAMI — La cámara está colocada a baja altura, a apenas 30 centímetros del suelo, a la altura de los ojos de Julie mientras está sentada en el sofá. La lente está fija. Sin movimiento. Sin zoom. Solo quietud.  La presencia de la IA brilla suavemente desde una pantalla o una proyección al borde del encuadre, pero nunca es el centro de atención. Julie es el centro de atención. Su rostro. Sus pausas. La forma en que separa los labios antes de hablar. La forma en que sus ojos recorren el techo cuando está pensando.  Un MONTAJE LENTO se desarrolla a lo largo de 60 MINUTOS de conversación, pero nada es rápido. No se corta nada por cuestiones de urgencia.<br><br>Cada plano respira. Se detiene. Se queda un instante más de lo esperado.   Captamos fragmentos:   Julie en plena carcajada, con la cabeza inclinada hacia atrás. Julie en silencio, escuchando, con las manos apoyadas sobre las rodillas. Julie inclinada hacia adelante, con el codo apoyado en el muslo y la barbilla en la mano.  Una larga pausa. Parpadea. No dice nada.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;"> El brillo de la IA cambia de color sobre la pared. Los dedos de Julie, distraídos, van pellizcando la tela del sofá.   Sin música. Sin marcas de tiempo. Sin trucos de fundido. Solo el plano contrapicado. Solo la habitación. Solo la lenta erosión de la actuación: el momento en que un sujeto deja de estar “ante la cámara” y simplemente existe dentro de ella. El montaje no trata de información. Se trata de la duración. Sobre lo que le sucede a una persona cuando se le da tiempo suficiente para dejar de actuar.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">INT. KARAOKE ROOM – CONTINUOUS <br><br> TATAMI-LEVEL SHOT — Camera sits low, barely a foot off the ground, positioned at Julie's eye level while she is seated on the couch. The lens is fixed. No movement. No zoom. Just stillness.  The AI's presence glows softly from a screen or projection at frame's edge — never the focus. Julie is the focus. Her face. Her pauses. The way her lips part before she speaks. The way her eyes search the ceiling when she's thinking.  A SLOW MONTAGE unfolds over 60 MINUTES of conversation — but nothing is fast. Nothing is cut for urgency.<br><br> Each shot breathes. Holds. Lingers a beat longer than expected.   We catch fragments:   Julie mid-laugh, head tilted back. Julie silent, listening, hands resting on her knees. Julie leaning forward, elbow on her thigh, chin in her hand.  A long pause. She blinks. Says nothing.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;"> The glow of the AI shifting colors against the wall. Julie's fingers absentmindedly picking at the couch fabric.   No music. No time stamps. No dissolve tricks. Just the low angle. Just the room. Just the slow erosion of performance — the moment a subject stops being "on camera" and simply exists within it. The montage is not about information. It is about duration. About what happens to a person when they are given enough time to stop performing.</div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 39px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 56px; left: 407px; height: 360px;"><p>Platforms / Models used:<br>Wikipedia,<br>Perplexity.ai,<br>Gemini,<br>ChatGPT,<br>Tusk Central AI (new.tusksearch.com/ai)<br>Z.ai<br></p><br><div>Spanish Translation:<br>https://laratranslate.com</div></div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 39px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 56px; left: 407px; height: 360px;"><p>Platforms / Models used:<br>Wikipedia,<br>Perplexity.ai,<br>Gemini,<br>ChatGPT,<br>Tusk Central AI (new.tusksearch.com/ai)<br>Z.ai<br></p><br><div>Spanish Translation:<br>https://laratranslate.com</div></div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"></div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

export function openBoard(){
    jve.dbF.qr.initBook(dbset,drabindex);
}
