var vt = [];
var vte = [];
export var dbset = [];

var dbbtn = `<div id="dbbutton" class="textshirt dbbutton" style="top: 91.3769%; left: 95.4652%; width: 36px; height: 36px;"><div id="dbbutton2" class="dbbutton textshirt circleshirt" style="height: 36px; width: 36px; top: 91.3769%; left: 95.4652%; background-color: rgb(255, 255, 255); border-color: rgb(255, 255, 255); color: rgb(255, 255, 255);"></div><div id="dbbutton3" class="dbbutton textshirt circleshirt" style="height: 22px; width: 22px; top: 92.4896%; left: 96.0907%;"></div></div>`;

//to adjust
export const dbtitle = 'Olives_G';
const defaultspeed = 25;
const transws = ' wspeed_10';
const drabindex = 'Olives_G';

const bimgpath = storyline.jsonUrl+'./drawboard/bimg/openbook-581128.jpg';
var dbbg =`<div id="dbbackg" class="textshirt imageshirt" style="left: -14px; top: -72px; width: 1280px; height: 853px;"><img src="`+bimgpath+`"></div>`;
dbbg += '<style>.textshirt{color:#000;font-family:EBGaramond;}</style>';

vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">Unas Vacaciones Especiales</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;" contenteditable="false">Este viaje me llevó meses de espera hasta que finalmente llegó. Descubrí que hay dos formas de esperar a que algo suceda: la primera es analizar cómo el acontecimiento inminente podría repercutir en tu vida, y la segunda es echarle un vistazo de vez en cuando al calendario —o a cualquier otro dispositivo que mida el tiempo— para ver si está lo suficientemente cerca como para justificar una reacción.  Elegí la primera opción, aunque en realidad no puedo atribuirme el mérito por ello. No fue la disciplina lo que me impulsó; fue el acontecimiento en sí. Algunas cosas irradian una calidez hacia la que inevitablemente te inclinas. Es el tipo de acontecimiento hacia el que te sientes atraído por una preferencia consciente y activa, en lugar de por un simple consenso universal sobre cómo funciona el mundo. Digamos simplemente que es cuestión de suerte. Siempre he querido ir a Italia. El lugar parece irradiar una sensación de grandeza, algo a lo que todos los peregrinos espirituales aspiran. Pero eso no es de lo que quería formar parte. Cuando vaya allí, no quiero ir a ninguna iglesia ni conocer al papa; solo quiero respirar el aire del campo. </div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Sé que suena contradictorio, pero es simplemente cómo siempre lo he imaginado en mi mente. Greg Rubin, un hombre de poco más de cuarenta años, se quita las gafas de media montura y deja a un lado el libro que estaba leyendo. Entrecierra mucho los ojos y se frota la frente y los ojos con una mano, como si hubiera estado trabajando en una carnicería todo el día. No sé cómo se supone que este libro me vaya a ayudar a hacer algo significativo para mejorar lo que estoy haciendo, que es ofrecer visitas guiadas a una plantación de olivos. ¿Se suponía que debía entender mejor cómo piensan los turistas cuando se les muestra una gran cantidad de árboles de aspecto centenario y con una longevidad extraordinaria, lo que me permitiría hacer que participaran en el recorrido por segunda, tercera o cuarta vez? ¿Cómo va a suceder eso? ¿Cómo es siquiera posible? Un olivar es atractivo porque simplemente lo es. No puedo controlar cómo funciona la mente de cada turista, y si prefieren los antiguos edificios de piedra o al Papa en Roma antes que las maravillas de la biología, entonces... ningún libro podrá decirme cómo cambiar sus preferencias. Echó un vistazo por un momento a la portada del libro que estaba sobre la mesa y luego fijó la mirada por la ventana.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">Special Holiday</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;">This trip took me months waiting for it to finally arrived, i found that there's 2 ways of waiting  for something to happen, 1 is to study how the impending event might ripple through your life and 2 is to keep glancing at the calendar - or any other time measurement devices - from time to time to see if its close enough for any justified reaction.  I chose the former, though I can't really take the credit for that. It wasn't discipline that carried me; it was the event itself. Some things radiate a warmth you can't help but lean toward— it's a type of event that you gravitate towards through an active conscious preference rather than just a universal agreement for how the world works. Let's just call it being lucky. <br class=""> Italy, i have always wanted to go there, the place seems to broadcast a sense of grandeur, something that every spiritual pilgrim look towards but that's not what i wanted to be a part of, i never want to go to church or meet the pope when i go there, i just want to breathe the air of the countryside. sounds contradictory i know, but its just how i have always envisioned it in my mind.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Greg Rubin, a forty-something-year-old man, takes off his half-framed glasses and sets down the book he was reading. He squints hard and rubs his forehead and eyes with one hand, as if he'd been working in a butcher shop all day.<br><br> I don't know how this book is supposed to help me do anything meaningful to improve what I'm doing, which is running an olive grove plantation tour. Was I supposed to know better how tourists' minds work when they're shown a vast number of ancient-looking trees with extreme longevity—that would enable me to make them join the tour a second, third, fourth time? How is that going to happen? How is that even possible?<br> <br> An olive grove is attractive because it is attractive. I can't control how every tourist's mind works, and if they prefer ancient stone buildings or the Pope in Rome to the wonders of biology, then... no book can ever tell me how to change their preference.<br>  He glanced for a moment at the cover of the book on the table, then fixed his gaze out through the window.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};



vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">En la portada del libro se leía “Una iglesia entre olivos”.  La ilustración de la portada mostraba un olivo viejo y retorcido, con las ramas extendiéndose como si salieran de la superficie bidimensional.   Este no era el tipo de árbol que uno vería en una visita guiada a una plantación; era un árbol monumental. Lo que normalmente verías al unirte a un recorrido es un vasto jardín que se extendía por el paisaje, con hileras de olivos meticulosamente podados que se alzaban en perfecta armonía. Sus troncos retorcidos y sus copas cuidadosamente cuidadas son un testimonio de siglos de cultivo. Las hojas de color verde plateado brillaban a la luz del sol, proyectando sombras moteadas sobre el suelo. Esta escena serena y atemporal era un testimonio vivo de la relación perdurable entre los seres humanos y el olivo, una relación que ha dado forma a culturas, cocinas y paisajes a lo largo de la historia, no de una historia muy antigua, sino de milenios. El olivo más antiguo del mundo que aún produce aceitunas tiene alrededor de 6000 años, y la evidencia arqueológica sobre cuándo los seres humanos comenzaron a procesar y usar los aceites de oliva —para sus rituales y medicinas— se remonta aún más atrás en el tiempo, hasta hace unos 8000 años. </div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Esto es interesante, pero no atractivo. Lo que sí es atractivo es cómo el árbol logra su extrema longevidad, gracias a una combinación de adaptaciones estructurales únicas, capacidades regenerativas y una bioquímica protectora. En la base de un olivo, justo donde el tronco se une al sistema radicular, se encuentra una enorme protuberancia conocida como lignotúbero (u “ovolo” en italiano). Un lignotúbero es varias cosas a la vez: en primer lugar, es un “banco de yemas”, ya que este tejido contiene una vasta y densa reserva de yemas adventicias latentes. En segundo lugar, es una “bóveda de carbohidratos” que almacena enormes cantidades de almidones y nutrientes. Este lignotúbero subterráneo permanece intacto ante cualquier situación externa adversa y, con rapidez, hace brotar nuevos vástagos genéticamente idénticos para reconstruir todo el árbol que haya resultado dañado.   Este proceso de regeneración de la corona radicular se debe a las células meristemáticas, que son células madre vegetales capaces de dividirse de forma continua y que pueden recrear un órgano vegetal completo a partir de pequeños fragmentos de tejido. Cada nueva parte de la planta, ya sean brotes, raíces u hojas, tanto si procede de una semilla como de la regeneración, se origina en el tejido meristemático. </div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">The book cover read "A Church between the Olives".  The cover art depicted an old, gnarled olive tree, the branches reaching out as if popping out of the two-dimensional surface.   This wasn't the kind of tree you'd see on a plantation tour; it was a monumental tree. <br><br>what you'd typically see by joining a tour is a vast garden that stretched across the landscape, rows of meticulously pruned olive trees that stood in perfect harmony, their gnarled trunks and carefully managed canopies a testament to centuries of cultivation. The silvery-green leaves shimmered in the sunlight, casting dappled shadows on the ground below. This serene and timeless scene was a living testament to the enduring relationship between humans and the olive tree, a relationship that has shaped cultures, cuisines, and landscapes throughout history - not grandpa-old history, millennia. <br><br>The oldest and still producing olive tree in the world dates to around 6000 years old and the archeological evidence for when human have started processing, and using the olive oils - for their rituals and medicines - goes even further back in time to about 8000 years.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">This is interesting, but not attractive, what's attractive is how the tree gets to have its extreme longevity, which are a combination of unique structural adaptations, regenerative capabilities, and protective biochemistry. <br><br>At the base of an olive tree, right where the trunk meets the root system, lies a massive swelling known as a lignotuber (or ovolo in Italian), a lignotuber is several things at once, first it is a Bud Bank, this tissue contains a vast dense reserve of dormant adventitious buds. second, it is a Carbohydrate Vault which stores enormous amounts of starches and nutrients. This subterranean lignotuber remains intact through any adverse external situations and quickly sends up new genetically identical shoots to rebuild the entire tree that was damaged.   This process of root crown regeneration comes from the meristematic cells, plant stem cells capable of continuous division that can recreate an entire plant organ from a small tissue fragments. <br>every new plant part, shoots, roots, leaves - whether from seed or regeneration - originates from meristematic tissue.</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 43px; left: 401px; height: 360px;">Luego está el escudo bioquímico compuesto por oleuropeína e hidroxitirosol, los compuestos fenólicos concentrados en las hojas, la corteza y el fruto que le dan a las aceitunas su sabor amargo. En realidad, estos actúan como barreras químicas naturales contra patógenos, hongos e insectos herbívoros. También contienen taninos, que se acumulan en grandes cantidades en la madera para ahuyentar a los insectos y a las bacterias causantes de la descomposición. Además de lo mencionado, hay otros factores que les ayudaron a sobrevivir en la naturaleza, pero... demasiado contenido científico puede restar atractivo. Ya estamos en noviembre y la temporada de cosecha ya ha comenzado, una época emocionante pero ajetreada para todos los involucrados. En su subconsciente resuena la idea de que la economía se verá impulsada por lo que ellos mismos trabajan con sus manos. Un solo olivo puede producir anualmente hasta 80 kg de frutos en condiciones óptimas, aunque el promedio es de unos 15 a 40 kg. El aceite que se puede obtener de esta cantidad representa aproximadamente el 15-25 %. Por lo tanto, si esperamos una producción de 40 kg, podríamos obtener entre 6 y 10 litros de aceite,cuyo precio oscila entre $10 y $15 por litro, lo que equivale a $60-$150 por un solo</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="word-break: break-word; width: 335px; white-space: normal; top: 36px; left: 786px; height: 360px;">olivo maduro y productivo. Teniendo en cuenta los costos de mano de obra, cosecha, molienda, agua y mantenimiento, los olivares comerciales suelen generar ingresos netos de entre $ 1500 y 4500 por acre al año con una gestión estándar. En promedio, una plantación de olivos en España, que tiene el tamaño medio de explotación más grande entre los principales países europeos productores de olivo, ocupa alrededor de 14,3 acres. Sin embargo, las visitas guiadas a las plantaciones constituyen un aporte económico aparte, ya que se enmarcan en el turismo y no en la agronomía, ni en la gastronomía, ni en la olivicultura, ni en la silvicultura, ni en... Greg murmura sus pensamientos en voz alta, pero no demasiado fuerte; lo justo para que alguien cerca de él lo escuche, pero no alguien que esté fuera de la ventana o al otro lado de la habitación. De repente, piensa en cómo mejorar el flujo de ingresos de la plantación gracias a las visitas guiadas: ¿y si... invito al autor de este libro a venir a visitar el jardín y veo si puede escribir un nuevo libro sobre él? Este libro solo roza superficialmente el tema de las visitas guiadas a plantaciones de olivos, al incluirlo como una breve mención. En cambio, un libro centrado específicamente en este tema podría contribuir aún más a dar a conocer esta actividad entre los posibles turistas. Debo enviarle una carta.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Then there's the biochemistry shield composed of Oleuropein and Hydroxytyrosol, the Phenolic compounds concentrated in the leaves, bark, and fruit that give olives their bitter taste actually act as natural chemical barriers against pathogens, fungi, and herbivorous insects. <br>They also have Tannins which are heavily accumulated in the wood to deter insects and decay-causing bacteria.  there are other things as well that helped them survive nature aside from what is mentioned, but... too much science can reduce its attractiveness. <br>Its November now and the harvest season has already begun, exciting but busy time for everybody involved, their subconscious is filled with how the economy is going to be run by what they are handling by their hands.<br><br> a single olive tree can anually produce of up to 80kg of fruits in an optimal condition, with the average is about 15-40kg, the oil product that can come from this is about 15-25%, so if we expect it to be 40kg then we could have 6-10L of oil which is priced at $10-15/L meaning $60-150 from a single mature productive tree.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Accounting for labor, harvesting, milling, water, and maintenance, commercial groves typically net $1,500–4,500 per acre annually under standard management.<br> On average, olive plantation in Spain - the largest average farm size among major European olive-producing nations - is about 14.3 acres (5.8 hectares), but plantation tours are a separate addition to the economy, it involves tourism not agronomy nor gastronomy nor Oleiculture, nor silviculture nor ... Greg mumbles his thoughts out loud, but not too loud, just enough for someone near him to hear, but not someone outside the window or across the room.<br><br>Suddenly he thinks about how to improve the flow of income of the plantation from guided tours: what if... i invite the author of this book to come and visit the garden and see if he can write a new book about it? this book only touches the surface on the topic of olive grove plantation tour, it coincide with it by including it as a cameo while a book that centers on this very topic itself can help even further in boosting awareness of this activity for potential tourists. i must send him a letter.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;">2001, La odisea de Seattle</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;">Mi indemnización por despido de Initech había sido generosa, sobre todo porque la empresa dejó de existir unos quince minutos después de que me la entregaran. Un día era Arquitecto Sénior de Soluciones, un cargo que implicaba pasar diez horas al día convirtiendo los delirios de un CEO en esquemas de bases de datos. Al día siguiente, era un hombre con una silla ergonómica muy cara y ningún lugar donde sentarse.  Eso fue en la primavera de 2001. Seattle estaba empapada por una llovizna gris y por la desesperación silenciosa de otros mil trabajadores del sector tecnológico que acababan de perder su empleo. La burbuja puntocom no estalló tanto como emitió un sonido parecido a un suspiro de decepción, y luego todo el dinero simplemente… se evaporó. Mis opciones sobre acciones se convirtieron en papel tapiz decorativo. Mi buscapersonas, una reliquia de una época más frenética, yacía en silencio sobre el mostrador, como una pequeña lápida de plástico para mi carrera. No me entró el pánico. Eso habría requerido energía. En cambio, hice lo que cualquier persona sensata haría cuando se derrumba el cimiento de su vida: no hice nada.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt cke_focus" style="width: 335px; white-space: normal; top: 33px; left: 786px; height: 360px;" contenteditable="false">Me senté en mi apartamento de Capitol Hill y observé cómo la lluvia dejaba rayas en las ventanas. Todas las mañanas iba caminando a la misma cafetería, pedía el mismo café de filtro y escuchaba a los baristas hablar de bandas de las que nunca había oído hablar. El pitido frenético de mi antigua vida fue reemplazado por el suave zumbido de un refrigerador y el tintineo lejano de un tranvía. Mi esposa, Elena, se había ido el año anterior por una razón que era a la vez concreta y vaga, algo relacionado con que yo era “un fantasma en mi propia vida”. En ese momento, pensé que estaba exagerando. Ahora, con todo el ruido desaparecido, me di cuenta de que probablemente tenía razón. Héctor Rivera hacía mucho tiempo que había dejado de ser una persona; era simplemente un conjunto de funciones y protocolos. Sin el sistema para ejecutarlas, yo simplemente estaba… inactivo. Así que empecé a escribir. No para nadie, solo para mí. Era una forma de desfragmentar mi cerebro. Escribí sobre las palomas de mi escalera de incendios. Escribí sobre el tono específico de gris que adquiere el cielo antes de un verdadero aguacero. Escribí largas y divagantes descripciones de mis antiguos compañeros de trabajo, dándoles a todos finales trágicos y poéticos. Fue un proceso lento y meticuloso, como limpiar una habitación muy grande y llena de polvo. Las palabras llenaron el silencio.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;">2001, Seattle Odyssey</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 95px; left: 407px; height: 360px;">My severance package from Initech had been a generous one, mostly because the company had ceased to exist about fifteen minutes after they handed it to me. One day I was a Senior Solutions Architect, a title that meant I spent ten hours a day translating the fever dreams of a CEO into database schemas. The next, I was a man with a very expensive ergonomic chair and nowhere to sit.  That was the spring of 2001. Seattle was awash in a grey drizzle and the quiet desperation of a thousand other newly-unemployed tech workers. The dot-com bubble didn't so much burst as it made a sound like a disappointed sigh, and then all the money just… evaporated. My stock options became decorative wallpaper. My pager, a relic of a more frantic time, sat silent on the counter, a small plastic tombstone for my career.<br><br>  I didn't panic. That would have required energy. Instead, I did what any sensible person would do when their life’s foundation dissolves: I did nothing.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` cke_focus" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;" contenteditable="false"><p>I sat in my Capitol Hill apartment and watched the rain streak the windows. I walked to the same coffee shop every morning, ordered the same drip coffee, and listened to the baristas talk about bands I’d never heard of. The frantic beeping of my old life was replaced by the gentle hum of a refrigerator and the distant clang of a trolley. My wife, Elena, had left the year before for a reason that was both specific and vague, something about me being "a ghost in my own life." At the time, I thought she was being dramatic. Now, with all the noise gone, I realized she was probably right. Hector Rivera hadn't been a person for a long time; he was just a collection of functions and protocols. Without the system to run them, I was just… dormant.<br>
So I started writing. Not for anyone, just for me. It was a way to defragment my brain. I wrote about the pigeons on my fire escape. I wrote about the specific shade of grey the sky turns before a real downpour. I wrote long, rambling character sketches of my former colleagues, giving them all tragic, poetic endings. It was a slow, meticulous process, like cleaning a very large, very dusty room. The words filled the silence.</p>
</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};

vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Una de esas habitaciones cubiertas de polvo era mi pasado. Una tarde, mientras borraba archivos antiguos de mi portátil, me topé con una dirección de correo electrónico de hace una eternidad. Javier. Crecimos juntos en Yakima, dos críos sudando en los mismos huertos. Él fue el que se escapó, o mejor dicho, el que tomó un camino diferente. Mientras yo aprendía a programar en C, él aprendía sobre el pH del suelo y el riego; ahora se dedica a plantar olivos.  Le envié un correo breve. Solo algo del tipo «Hola, ¿qué tal?». Me respondió en menos de una hora. Dijo que se había enterado de la crisis tecnológica. Dijo que lo sentía. Dijo que había estado siguiendo mi carrera, de una forma que parecía más propia de un gestor de carteras que de un amigo. Intercambiamos unos cuantos correos electrónicos y luego unas cuantas llamadas telefónicas. Su voz seguía siendo la misma, grave y ronca, pero las pausas eran más largas, más meditadas. Al final, fue al grano.  «Escucha, Héctor», me dijo una noche, con su voz retumbando grave al otro lado de la línea. «Sé que no estás haciendo gran cosa. Me vendría bien alguien como tú».  «¿Alguien como yo?», pregunté, observando cómo una mosca zumbaba alrededor de la luz de la cocina. «No tengo ni idea de aceitunas, Javi».</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">«A menos que tengan una interfaz de línea de comandos».  No se rió. Hubo una larga pausa, de esas que antes me hacían comprobar si se había cortado la línea.  «Además», continué, «estás en la maldita Italia. En Apulia, según dijiste. No es precisamente un viaje de fin de semana. Me costaría una fortuna que no tengo solo llegar hasta allí. ¿Y luego qué? ¿Me presento, con el sombrero en la mano, y trabajo para tu familia? Claro que conocía la cocina de tu madre y la furgoneta de tu padre, pero eso no es un currículum».  «Héctor», dijo, con voz paciente, como si le estuviera explicando algo sencillo a un niño lento. «El billete está pagado. El alojamiento está pagado. Serías un idiota si dijeras que no. Y tú no eres un idiota. Simplemente… estás en un punto muerto».  Odiaba lo acertado que era eso. La vida que describía era atractiva. Tranquila. Previsible. Pero había un trasfondo en sus palabras, una corriente subterránea bajo la superficie tranquila. Hablaba de «mover producto», de «gestionar las relaciones con los proveedores», de ciertas «familias» de la zona que eran las únicas que podían garantizar una cosecha sin contratiempos.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">One of those dust-covered rooms was my past. I was deleting old files from my laptop one afternoon when I came across an email address from a lifetime ago. Javier. We grew up together in Yakima, two kids sweating in the same orchards. He was the one who got out, or rather, went a different direction. While I was learning to code in C, he was learning about soil pH and irrigation, now he's planting olives.  I sent him a short email. Just a "Hey, how's it going" kind of thing. He replied within an hour. He said he’d heard about the tech crash. He said he was sorry. He said he’d been following my career, in a way that felt less like a friend and more like a portfolio manager. We traded a few emails, then a few phone calls. His voice was the same, low and gravelly, but the pauses were longer, more considered.  <br><br>Eventually, he got to the point.  "Listen, Hector," he said one night, his voice a low rumble on the other end of the line. "I know you're not doing much. I could use a man like you."  "A man like me?" I asked, watching a fly buzz against the kitchen light. "I don't know the first thing about olives, Javi.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Unless they have a command-line interface."  He didn't laugh. There was a long pause, the kind that used to make me check if the line had dropped.  "Plus," I continued, "you're in freakin' Italy. Puglia, you said. That's not exactly a weekend commute. It'd cost me a fortune I don't have just to get there. And then what? I show up, hat in hand, and work for your family? Sure i knew your mother's cooking and your father's truck but that's not a resume."  "Hector," he said, his voice patient, like he was explaining something simple to a slow child. "The ticket's covered. The housing's covered. You'd be an idiot to say no. And you're not an idiot. You're just… paused."  I hated how accurate that was. <br><br> The life he described was appealing. Slow. Predictable. But there was an undercurrent in his words, a riptide beneath the calm surface. He talked about "moving product," about "managing relationships with suppliers," about certain "families" in the area who were the only ones who could ensure a smooth harvest.</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Mencionó el «trabajo húmedo» ocasional que requería un nuevo sistema de riego, y la forma en que lo dijo, con una ligera pausa antes de pronunciar la frase, me hizo pensar que no se refería solo a las tuberías. Le dije que lo pensaría. Esa noche, no pude dormir. El silencio de mi piso me resultaba diferente. Ya no era tranquilo; era vacío. El dinero de mi indemnización se estaba acabando. Lo que escribía no era más que un montón de palabras que no llevaban a ninguna parte. <br><br>  Una semana después, estaba en el asiento del medio de un vuelo de Delta a Roma, encajonado entre un bebé que lloraba y un hombre que olía a cigarrillos de mentol y a arrepentimiento. Había facturado una maleta. Contenía todo lo que poseía y que aún me importaba: un portátil, algo de ropa para cambiarme y una caja de zapatos llena de fotografías que no había mirado en años.  El vuelo duró once horas. Vi tres películas que no recuerdo y comí dos comidas que no sabían a nada. En algún punto sobre el Atlántico, me di cuenta de que llevaba seis años sin salir del noroeste del Pacífico. La última vez fue para una conferencia en San José. Antes de eso, mi luna de miel. Ninguna de las dos cosas acabó bien.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Aterrizamos en Roma al amanecer. El aeropuerto era un caos, una sinfonía de anuncios en un idioma que no hablaba y gestos que no entendía. Encontré mi vuelo de conexión a Bari tras cuarenta minutos dando vueltas en círculos y haciendo la misma pregunta a tres personas diferentes. Nadie sonreía. No pasaba nada. Yo tampoco sonreía.<br>  El vuelo a Bari fue corto. Demasiado corto. No estaba preparado para llegar. Pero el avión aterrizó de todos modos, indiferente a mis sentimientos.  Javier me esperaba fuera de la zona de recogida de equipajes. Parecía más mayor de lo que recordaba, con el rostro bronceado y arrugado como el cuero viejo. Estaba apoyado contra una camioneta Fiat destartalada que había vivido mejores décadas.  «Héctor», dijo, sin que fuera exactamente una pregunta.  —Javi —dije, sin que fuera del todo una respuesta.  Nos dimos la mano. Su apretón era seco y firme, el apretón de manos de un hombre que había aprendido hacía mucho tiempo que la calidez era una moneda que no podía permitirse gastar.  <br>El trayecto hasta la arboleda duró una hora. La carretera serpenteaba por pueblos que parecían haber sido pintados por alguien que solo tuviera acceso al ocre y al verde desvaído.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">He mentioned the occasional "wet work" needed for a new irrigation system, and the way he said it, with a slight pause before the phrase, made me think he wasn't just talking about pipes.  I said I’d think about it. That night, I couldn't sleep. The quiet of my apartment felt different. It wasn't peaceful anymore; it was empty. The money from my severance was running out. My writing was just a pile of words going nowhere.  <br><br>  A week later, I was in a middle seat on a Delta flight to Rome, wedged between a crying infant and a man who smelled like menthol cigarettes and regret. I had checked one bag. It contained everything I owned that still mattered: a laptop, a few changes of clothes, and a shoebox of photographs I hadn't looked at in years.  The flight was eleven hours. I watched three movies I don't remember and ate two meals that tasted like nothing. Somewhere over the Atlantic, I realized I hadn't left the Pacific Northwest in six years. The last time was a conference in San Jose. Before that, my honeymoon. Neither ended well.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">We landed in Rome at dawn. The airport was chaos, a symphony of announcements in a language I didn't speak and gestures I didn't understand. I found my connecting flight to Bari after forty minutes of walking in circles and asking three different people the same question. Nobody smiled. That was fine. I wasn't smiling either.<br>  The flight to Bari was short. Too short. I wasn't ready to arrive. But the plane landed anyway, indifferent to my feelings.  Javier was waiting for me outside baggage claim. He looked older than I remembered, his face tanned and lined like old leather. He was leaning against a battered Fiat pickup that had seen better decades.  "Hector," he said, not quite a question.  "Javi," I said, not quite an answer.  We shook hands. His grip was dry and firm, the handshake of a man who had learned long ago that warmth was a currency he couldn't afford to spend.  <br>The drive to the grove took an hour. The road wound through towns that looked like they had been painted by someone who only had access to ochre and faded green.</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Los ancianos se sentaban a la puerta de las cafeterías, observando pasar los coches con el interés distante de quienes lo han visto todo y ya no esperan nada.  Entonces terminaron los pueblos y comenzó el campo. No se parecía en nada a Washington. La tierra era seca, antigua, esculpida en colinas bajas que parecían respirar bajo el calor. Los olivos se extendían en todas direcciones, con sus hojas plateadas y temblando al viento. Era hermoso de una forma que parecía indiferente a ser observado.  Javier no hablaba mucho. Yo tampoco. El silencio entre nosotros no resultaba incómodo. Simplemente… estaba ahí. Como la tierra.  <br><br>Dejamos la carretera principal para tomar un camino de grava que conducía a un recinto de edificios bajos de piedra. Un perro ladraba en algún lugar a lo lejos. Una mujer con un vestido negro estaba de pie en un porche, observándonos mientras nos acercábamos. No nos saludó con la mano.  «Hogar», dijo Javier, y la palabra quedó suspendida en el aire como humo.  Me bajé de la camioneta. El suelo estaba duro bajo mis pies. El sol lo inundaba todo. No tenía ni idea de qué hacía allí.  Eso, al menos, me resultaba familiar.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">El trabajo era básicamente igual que el anterior, solo que con términos diferentes. En lugar de gestionar el tiempo de actividad de los servidores, gestionaba los plazos de entrega. En lugar de optimizar código, optimizaba rutas de envío. En lugar de tratar con vicepresidentes de la empresa, trataba con hombres que llevaban trajes caros y nunca sonreían. Redactaba correos electrónicos cuidadosamente formulados para que no contuvieran ninguna información. Elaboraba hojas de cálculo que cuadraban las cuentas de una forma que era a la vez perfectamente lógica y completamente ficticia.  Se me daba bien. No era más que otro sistema.<br><br>  El dinero empezó a llegar. No era una nómina, sino una «compensación». Llegaba en bolsas de lona que olían ligeramente a fertilizante y a hierro. No hacía preguntas. Simplemente hacía lo que me decían, y las cifras de mi cuenta bancaria crecían como nunca lo habían hecho durante el boom. <br><br> Sigo escribiendo, pero ahora lo hago en una pequeña casa alquilada en los límites de la finca. Escribo bajo el zumbido de una luz fluorescente barata.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Old men sat outside cafés, watching the cars pass with the detached interest of people who had seen everything and expected nothing.  Then the towns ended, and the countryside began. It was nothing like Washington. The land was dry, ancient, carved into low hills that seemed to breathe in the heat. Olive trees stretched in every direction, their leaves silver and trembling in the wind. It was beautiful in a way that felt indifferent to being observed.  Javier didn't speak much. I didn't either. The silence between us wasn't uncomfortable. It was just… there. Like the land.  <br><br>We turned off the main road onto a gravel path that led to a compound of low stone buildings. A dog barked somewhere in the distance. A woman in a black dress stood on a porch, watching us approach. She didn't wave.  "Home," Javier said, and the word hung in the air like smoke.  I got out of the truck. The ground was hard beneath my feet. The sun was everywhere. I had no idea what I was doing here.  That, at least, was familiar.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">The job was essentially the same as my old one, just with different nouns. Instead of managing server uptime, I managed delivery schedules. Instead of optimizing code, I optimized shipping routes. Instead of dealing with corporate VPs, I dealt with men who wore expensive suits and never smiled. I wrote emails that were carefully worded to contain no information. I wrote spreadsheets that balanced accounts in a way that was both perfectly logical and completely fictional.  I was good at it. It was just another system.<br><br>  The money started to come in. Not a paycheck, but 'compensation'. It arrived in canvas duffel bags that smelled faintly of fertilizer and iron. I didn't ask questions. I just did what I was told, and the numbers in my bank account grew in a way they never did during the boom. <br><br> I still write, but now I write in a small, rented house on the edge of the property. I write under the hum of a cheap fluorescent light.</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 39px; left: 789px; font-size: 26px;">El resumen</div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">Escribo hasta bien entrada la noche, intentando plasmar en palabras el sonido de los nudillos de un hombre al crujir, o la forma en que un socio de «fuera de la ciudad» se toma su espresso, o el peso exacto de una bolsa de viaje en mis manos. Ya no soy un fantasma en mi propia vida. Tengo una función. Yo soy el sistema. <br class=""><br>Es una vida tranquila, una vida pausada, tal y como prometió Javier. Lo único es que el silencio ya no está vacío. Simplemente está a la espera.</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 90px; left: 785px; height: 360px;">OFICINA LOCAL DEL FBI,<br class=""> CIUDAD DE NUEVA YORK. 14 DE NOVIEMBRE DE 2001  -  7:42 DE LA MAÑANA<br> La luz fluorescente que había sobre la mesa de reuniones parpadeaba de vez en cuando, como un tic nervioso. Jeremy Roth no había dormido. El café que tenía en la mano se había enfriado hacía veinte minutos, pero seguía sujetándolo, como si fuera un atrezo en una obra de teatro unipersonal sobre cómo mantenerse despierto. <br>La agente Delgado estaba junto a la pizarra, destapando un rotulador con los dientes. «Bueno», comenzó Roth, «Isaac Romano». <br>Delgado escribió el nombre en mayúsculas. Lo subrayó dos veces. «Miembro de la mafia. Afiliado a la familia Gambino. Llevamos siguiéndole la pista desde el 96. Extorsión, usura, dos cadáveres que no podemos achacarle y un temperamento que le ha valido la expulsión de tres restaurantes en Little Italy». Dio un paso atrás. «Pero no tenemos nada nuevo. Lleva tranquilo desde el verano».</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 39px; left: 789px; font-size: 26px;">The Debrief</div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">I write late into the night, trying to put words to the sound of a man’s knuckles cracking, or the way a business associate from "out of town" drinks his espresso, or the precise weight of a duffel bag in my hands.  I am no longer a ghost in my own life. I have a function. I am the system. <br class=""><br>It’s a quiet life, a slow life, just as Javier promised. The only thing is, the silence isn't empty anymore. It's just waiting.</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 90px; left: 785px; height: 360px;">FBI FIELD OFFICE,<br> NEW YORK CITY. NOVEMBER 14, 2001  -  7:42 AM<br><br>  The fluorescent light above the conference table had a flicker that came and went like a nervous tic. Jeremy Roth hadn't slept. The coffee in his hand had gone cold twenty minutes ago, but he kept holding it, a prop in a one-man play about staying awake. <br><br>Agent Delgado stood by the whiteboard, uncapping a marker with her teeth. "So," Roth started, "Isaac Romano." <br><br>Delgado wrote the name in block letters. Underlined it twice. "Made guy. Gambino affiliate. Been on our radar since '96. Extortion, loansharking, two bodies we can't pin on him, and a temper that got him banned from three restaurants in Little Italy." She stepped back. "But we've got nothing new. He's been quiet since the summer."</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">«Silencio», repitió Roth. <br>«Silencio de iglesia. Lo cual, en el caso de Isaac, significa o que está enfermo, o que es listo, o que alguien de sus superiores le ha dicho que se quede quieto». <br>El agente Kowalski se inclinó hacia delante en su silla, con los codos apoyados en la mesa. Tenía el aspecto de un hombre que llevaba días masticando algo y estaba harto de su sabor. «Pero ahí está el quid de la cuestión. No está enfermo. Le hemos hecho un reconocimiento médico. No es listo… Bueno, lo es, pero no «tan» listo. Y nadie de sus superiores le está diciendo nada porque nadie de sus superiores sabe adónde ha ido a parar su dinero».<br> Roth dejó el café frío sobre la mesa. «Su dinero». <br><br>«Su dinero. Y mucho. Seis, siete millones, quizá más, movidos a través de cuentas ficticias en los últimos dieciocho meses. Todavía lo estamos rastreando». <br><br>El agente Ruiz, que había permanecido en silencio hasta ese momento, abrió una carpeta. «Ahí es donde entra en juego el nombre».</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">«¿Qué nombre?»<br> «Greg Rubin».<br> Se hizo el silencio en la sala. No un silencio dramático, sino ese tipo de silencio que se produce cuando tres personas llevan una semana discutiendo sobre algo y la cuarta persona que está en la sala no tiene ni idea de qué están hablando. Roth miró a Delgado. Luego a Kowalski. Y de nuevo a Ruiz. «¿Quién demonios es Greg Rubin?». Delgado y Kowalski intercambiaron una mirada. De esas que dicen: «¿Te encargas tú de esto o lo hago yo?». <br><br>«Es contable», declaró Delgado. <br>«Un contable».<br> «Lo era. Contable colegiado. Tenía un despacho en Bay Ridge. Cosas sin importancia: declaraciones de la renta, contabilidad de pequeñas empresas, un par de restaurantes, una funeraria. Nada que lo pusiera en nuestro punto de mira». <br>Kowalski resopló. «Hasta que empezó a llevar las cuentas de un tipo que llevaba las cuentas de Isaac Romano». Roth se recostó en la silla. Esta crujió. «Así que es un tipo de las finanzas. ¿Qué hizo, desviar fondos?».</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">"Quiet," Roth repeated. <br>"Church-quiet. Which for Isaac means either he's sick, or he's smart, or somebody above him told him to sit still." <br><br>Agent Kowalski leaned forward in his chair, elbows on the table. He had the look of a man who'd been chewing on something for days and was tired of the taste. "That's the thing, though. He's not sick. We ran his medical. He's not smart - I mean, he is, but not 'this' smart. And nobody above him is telling him anything because nobody above him knows where his money's been going."<br><br> Roth set the cold coffee down. "His money." <br><br>"His money. And a lot of it. Six, seven million, maybe more, moved through shell accounts over the last eighteen months. We're still tracing it." <br><br>Agent Ruiz, who had been silent until now, flipped open a folder. "That's where the name comes in."</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+` selected" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">"Which name?"<br> "Greg Rubin."<br> The room went still. Not dramatic-still. Just the kind of still that happens when three people have been arguing about something for a week and the fourth person in the room has no idea what they're talking about. Roth looked at Delgado. Then at Kowalski. Then back at Ruiz. "Who the hell is Greg Rubin?" Delgado and Kowalski exchanged a look. The kind of look that says 'you want to take this one or should I.'. <br><br>"He's an accountant," Delgado declared. <br>"An accountant."<br> "Was. CPA. Had a practice in Bay Ridge. Small-time stuff - tax returns, small business bookkeeping, a couple of restaurants, a funeral home. Nothing that would put him on our radar." <br>Kowalski snorted. "Until he started doing the books for a guy who did the books for Isaac Romano." Roth leaned back. The chair creaked. "So he's a financial guy. What'd he do, skim?"</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">«Esa es la cuestión», replicó Ruiz. «No lo sabemos. No se llevó nada. O, si lo hizo, lo hizo tan bien que no podemos detectarlo. Pero hace unos catorce meses, dejó de aparecer por la oficina. Su mujer presentó una denuncia por desaparición. Sus cuentas bancarias quedaron inactivas. Su coche apareció en un aparcamiento de larga estancia del aeropuerto JFK».<br> «JFK».<br> «Terminal 4. Salidas internacionales». Roth asintió lentamente. <br>«Así que se fue en avión». <br>«O quería que pensáramos que se había ido en avión». Delgado dio unos golpecitos en la pizarra. «Ahí es donde entra en juego Romano. Sacamos la lista de clientes de Rubin. La mayor parte es aburrida. Pero hay un nombre que no deja de aparecer: una sociedad de cartera llamada Verrazzano LLC. Que es una sociedad ficticia. Que es propiedad de otra sociedad ficticia. Que es propiedad de otra sociedad ficticia. Que, seis niveles más abajo, es propiedad de un tipo llamado Sal Petrucci». <br>«Petrucci», observó Roth. «El primo de Isaac». <br> «Su primo “favorito”. Con el que juega a las cartas los jueves. Al que pagó los estudios de su hija en Fordham».</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Kowalski echó la silla hacia atrás. Esta rozó el suelo. «Y esta es la parte que lleva seis días volviéndome loco. Rubin no solo llevaba las cuentas de Petrucci. También llevaba las cuentas “personales” de Petrucci. La hipoteca del tipo, la matrícula de su hijo, las tarjetas de crédito de su mujer. Y luego, tres semanas antes de que Rubin desapareciera, Petrucci transfirió dos millones de dólares a través de Verrazzano. Dos millones que no podemos rastrear. Dos millones que no aparecen por ninguna otra parte». <br><br>«Así que Rubin se los llevó», concluyó Roth.<br> «O Rubin los “vio”», replicó Delgado. «O Rubin los “movió”. No lo sabemos. Ese es el problema. Tenemos a un contable desaparecido, al primo de un mafioso y dos millones de dólares que se han esfumado. Y cada vez que intentamos vincular directamente a Rubin con Romano, nos topamos con un muro».<br><br>  «¿Qué tipo de muro?», preguntó Roth frunciendo el ceño.<br>  «De esos en los que nadie los ha visto nunca juntos en la misma habitación. De esos en los que el nombre de Rubin no aparece en ni un solo documento relacionado con Romano».</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">"That's the thing," Ruiz countered. "We don't know. He didn't skim. Or if he did, he did it so clean we can't see it. But about fourteen months ago, he stops showing up at his office. His wife files a missing persons report. His bank accounts go dormant. His car turns up in a long-term parking lot at JFK."<br><br> "JFK."<br> "Terminal 4. International departures." Roth nodded slowly. <br>"So he flew." <br>"Or he wanted us to think he flew." Delgado tapped the whiteboard. "That's where Romano comes in. We pulled Rubin's client list. Most of it's boring. But one name keeps popping up - a holding company called Verrazzano LLC. Which is a shell. Which is owned by another shell. Which is owned by another shell. Which, six layers down, is owned by a guy named Sal Petrucci." <br>"Petrucci," Roth observed. "Isaac's cousin." <br><br> "His 'favorite' cousin. The one he plays cards with on Thursdays. The one whose daughter he paid for to go to Fordham."</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Kowalski pushed his chair back. It scraped the floor. "And here's the part that's been driving me insane for six days. Rubin didn't just do Petrucci's books. He did Petrucci's 'personal' books. The guy's mortgage, his kid's tuition, his wife's credit cards. And then, three weeks before Rubin disappears, Petrucci moves two million dollars through Verrazzano. Two million that we can't trace. Two million that doesn't show up anywhere else." <br><br>"So Rubin took it," Roth concluded.<br> "Or Rubin 'saw' it," Delgado challenged. "Or Rubin 'moved' it. We don't know. That's the problem. We've got a missing accountant, a made guy's cousin, and two million dollars that vanished into thin air. And every time we try to connect Rubin to Romano directly, we hit a wall."<br><br>  "What kind of wall?" Roth frowned.<br>   "The kind where nobody's ever seen them in the same room. The kind where Rubin's name doesn't appear on a single document connected to Romano. </div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">«De esas en las que, por lo que sabemos, Greg Rubin e Isaac Romano nunca se han conocido», respondió Ruiz. <br><br> Kowalski se rió. No fue una risa alegre. «Lo cual es una tontería. Porque no llevas tres años llevando las cuentas del primo de alguien sin haber conocido nunca a ese tipo. No se transfieren dos millones de dólares a través de una sociedad ficticia sin saber de quién es el dinero».<br> «¿Así que crees que se está escondiendo?», espetó Roth. <br><br>«Creo que ha «desaparecido»», aventuró Kowalski. «Creo que vio algo que no debía, o hizo algo que no debía, y huyó. Y creo que Isaac Romano lo está buscando con el mismo ahínco que nosotros». <br><br>Delgado asintió. «Tenemos el teléfono de Romano intervenido. Nada explícito. Pero ha estado haciendo preguntas. Discretas. Sobre un tipo que solía encargarse de los impuestos de su primo. Sobre si alguien lo ha visto. Sobre si sigue en el país». <br>«¿Y?»</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">«Y nadie lo sabe. Esa es la cuestión. Nadie sabe dónde está Greg Rubin. Ni nosotros. Ni Romano. Ni su mujer. Ni su madre. Ni su compañero de golf. Nadie». Roth se quedó en silencio un momento. Luego se levantó, se acercó a la pizarra y se quedó mirando el nombre. Greg Rubin. Debajo, Isaac Romano. Entre ambos, un signo de interrogación. «¿Y qué me estás diciendo?», insistió. «Tenemos a un contable desaparecido, a un mafioso que lo está buscando y dos millones de dólares que nadie encuentra. Y vosotros tres lleváis una semana discutiendo sobre esto porque...»<br> «Porque Kowalski cree que Rubin está muerto», insistió Delgado.<br><br> «Yo “sé” que está muerto», corrigió Kowalski. «O más le valdría estarlo. Nadie desaparece con dinero de la mafia y vive para disfrutarlo. Está en una fosa poco profunda en Pine Barrens, o en el fondo del puerto, o en un vertedero de Jersey. Estamos perdiendo el tiempo intentando encontrar a un fantasma». <br><br>«Y yo creo que está vivo», intervino Ruiz. «Creo que es listo. Creo que vio lo que se avecinaba y se largó».</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">The kind where, as far as we can tell, Greg Rubin and Isaac Romano have never met." Ruiz answered. <br><br> Kowalski laughed. It wasn't a happy laugh. "Which is bullshit. Because you don't do books for a guy's cousin for three years and never meet the guy. You don't move two million dollars through a shell company and not know whose money it is."<br> "So you think he's lying low," Roth snapped. <br><br>"I think he's 'gone,'" Kowalski ventured. "I think he saw something he shouldn't have, or he did something he shouldn't have, and he ran. And I think Isaac Romano is looking for him just as hard as we are." <br><br>Delgado nodded. "We've got a wiretap on Romano's phone. Nothing explicit. But he's been asking questions. Quiet ones. About a guy who used to do his cousin's taxes. About whether anyone's seen him. About whether he's still in the country." <br><br>"And?"</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">"And nobody knows. That's the thing. Nobody knows where Greg Rubin is. Not us. Not Romano. Not his wife. Not his mother. Not his golf buddy. Nobody." Roth was quiet for a moment. Then he stood up, walked to the whiteboard, and stared at the name. Greg Rubin. Underneath it, Isaac Romano. Between them, a question mark. "So what are you telling me?" he pressed. "We've got a missing accountant, a mob guy who's looking for him, and two million dollars that nobody can find. And you three have been arguing about this for a week because - "<br> "Because Kowalski thinks Rubin's dead," Delgado insisted.<br><br> "I 'know' he's dead," Kowalski corrected. "Or he might as well be. You don't disappear with mob money and live to enjoy it. He's in a shallow grave in the Pine Barrens, or he's at the bottom of the harbor, or he's in a landfill in Jersey. We're wasting time trying to find a ghost." <br><br>"And I think he's alive," Ruiz chimed in. "I think he's smart. I think he saw what was coming and he got out.</div>`;
dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">«Creo que está en algún sitio con un nuevo nombre, un nuevo pasaporte y el conocimiento de un contable muy meticuloso sobre cómo pasar desapercibido». <br><br>Delgado se encogió de hombros. «Creo que no sabemos lo suficiente como para tener una opinión». <br><br>Roth se volvió hacia ellos. «Vale, esto es lo que vamos a hacer. Quiero toda la información sobre Verrazzano. Cada cuenta, cada transferencia, cada firma. Quiero saber quién firmó qué y cuándo. Quiero saber si el nombre de Rubin aparece en alguna parte, aunque sea en un memorándum. Y quiero saber quién más figuraba en la nómina de Petrucci».<br> «¿Y Romano?», preguntó Delgado. <br><br>«Romano sigue con las escuchas. Si encuentra a Rubin antes que nosotros, vamos a tener un problema mucho mayor que el de un contable desaparecido». <br>Kowalski negó con la cabeza. «Estás dando por hecho que sigue vivo».</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Roth lo miró. «Supongo que no lo sabemos, y hasta que lo sepamos, trataremos esto como una persecución. No como una investigación por asesinato. Todavía no». Cogió su café frío, dio un sorbo, hizo una mueca y lo volvió a dejar en la mesa. «Ahora, que alguien me diga por qué demonios un contable de poca monta de Bay Ridge arriesgaría su vida por dos millones de dólares».<br><br> Nadie respondió. La luz fluorescente parpadeó. Afuera, la ciudad seguía su curso sin ellos.</div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 49px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 54px; left: 407px; height: 360px;">I think he's somewhere with a new name, a new passport, and a very careful accountant's understanding of how to stay invisible." <br><br>Delgado shrugged. "I think we don't know enough to have an opinion." <br><br>Roth turned back to them. "Okay, here's what we're going to do. I want everything on Verrazzano. Every account, every transfer, every signature. I want to know who signed what and when. I want to know if Rubin's name shows up anywhere, even in a memo. And I want to know who else was on Petrucci's payroll."<br><br> "And Romano?" Delgado asked. <br><br>"Romano stays on the wiretap. If he finds Rubin before we do, we're going to have a much bigger problem than a missing accountant." <br><br>Kowalski shook his head. "You're assuming he's still alive." </div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 52px; left: 786px; height: 360px;">Roth looked at him. "I'm assuming we don't know, and until we do, we treat this like a manhunt. Not a murder investigation. Not yet." He picked up his cold coffee, took a sip, grimaced, and set it back down. "Now, somebody tell me why the hell a small-time accountant from Bay Ridge would risk his life for two million dollars."<br><br> Nobody answered. The fluorescent light flickered. Outside, the city went on without them.</div>`;

dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


vt=[];vte=[];
vt[vt.length]=`<div id="text_86" class="textshirt mergershirt" style="top: 39px; left: 406px; font-size: 26px;"></div>`;
vt[vt.length]=`<div id="text_83" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 56px; left: 407px; height: 360px;">Platforms / Models used:<br>Wikipedia,<br> DeepSeek, <br> Perplexity.ai, <br>Gemini,<br> ChatGPT,<br> Tusk Central AI (new.tusksearch.com/ai)<br><br>Spanish Translation:<br> https://laratranslate.com<br>https://www.deepl.com/en/translator</div>`;
vt[vt.length]=`<div id="text_84" class="textshirt mergershirt" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"></div>`;
vte[vte.length]=`<div id="text_86" class="textshirt mergershirt`+transws+`" style="top: 39px; left: 406px; font-size: 26px;"></div>`;
vte[vte.length]=`<div id="text_83" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 56px; left: 407px; height: 360px;">Platforms / Models used:<br>Wikipedia,<br> DeepSeek, <br> Perplexity.ai, <br>Gemini,<br> ChatGPT,<br> Tusk Central AI (new.tusksearch.com/ai)<br><br>Spanish Translation:<br> https://laratranslate.com<br>https://www.deepl.com/en/translator</div>`;
vte[vte.length]=`<div id="text_84" class="textshirt mergershirt`+transws+`" style="width: 335px; white-space: normal; top: 44px; left: 786px; height: 360px;"></div>`;


dbset[dbset.length] = {dbbg:dbbg,dbbtn:dbbtn,vt:vt,vte:vte};


export function openBoard(){
    jve.dbF.qr.initBook(dbset,drabindex);
}
