var shdtxt=`Estoy luchando con el concepto de economía de la atención, ¿por qué dice que la información consume nuestra atención en lugar de que usemos nuestra atención para consumir la riqueza de información disponible? ¿Por qué la flecha va en la dirección equivocada? Es debido a las notificaciones automáticas de la plataforma relacionada que utilizamos y su estrategia para que su oferta llegue al otro lado y se note, pero eso es todo...
Pero dado que la "riqueza de información" es de alguna manera administrada por esas plataformas y su "estrategia", ¿tenemos que participar en su modelo de economía? Pero entonces... entonces no existe la riqueza de información, es simplemente... un nuevo modelo de economía centrado en la información.
La frase '"la información consume atención"' puede sonar al revés al principio, casi como si la información fuera una criatura hambrienta que se come tu cerebro mientras estás sentado, indefenso.
Frase dramático, muy humano. Pero hay una razón por la que la flecha apunta en esa dirección. La idea original proviene del economista y científico cognitivo Herbert A. Simon.
Su argumento fue aproximadamente el siguiente: > Una gran cantidad de información crea una pobreza de atención. No porque la información sea mala, sino porque la atención es limitada.
Piénselo de esta manera: Información = abundante. Atención = escasa. La escasez crea economía.
Si son diez libros y tienes diez años, no hay problema. Si hoy llegan diez millones de vídeos, feeds, artículos, alertas, podcasts, ensayos, chats de IA y transmisiones en vivo, su atención se convierte en el cuello de botella.
Así pues, la frase "la información consume atención" describe una "relación de recursos". Como: Los coches consumen combustible. El software consume memoria. La información consume atención.
Esto "no" significa que no tengas agencia. Significa que la exposición a la información tiene un costo cognitivo.
Ahora tu segunda idea es donde las cosas se ponen interesantes. Dijiste: > tal vez se trata principalmente de plataformas que empujan cosas hacia nosotros.
En parte sí, pero no del todo. En realidad, aquí hay dos capas. Capa 1: La atención como economía cognitiva natural. Esto existe incluso sin plataformas modernas.
Imagina una biblioteca gigante. Todavía no puedes leerlo todo. Cada libro compite por horas de tu vida. La escasez de atención existe antes que los algoritmos, antes de los teléfonos inteligentes, antes de las notificaciones.
Así que "existe" algo llamado una "riqueza de información". El problema es la abundancia.
Ahora ingrese a la Capa 2. Economía de atención mediada por plataforma. Esta es la versión moderna a la que la gente suele referirse.
Las plataformas no se limitan a almacenar información. Lo clasifican. Lo recomiendo. personalizarlo. optimizar la entrega. medir el compromiso. competir por volver a visitarnos. Esto lo cambia todo.
Porque ahora la atención misma se vuelve económicamente valiosa. ¿Por qué? Porque la atención se puede convertir en: ingresos publicitarios. suscripciones. datos. influencia. lealtad a la marca. poder político o cultural.
Así que la información se parece menos a una biblioteca y más a un mercado o un casino. Las estanterías ya no son pasivas. Dicen tu nombre.
Por eso la flecha te resulta sospechosa. Instintivamente imaginas la información como material pasivo: > "Utilizo la atención para consumir información".
Eso es cierto en un modelo de biblioteca clásico. Pero en los sistemas digitales modernos, la información suele estar "activa y empaquetada estratégicamente" para captar su atención.
Entonces ambas flechas existen. Tu perspectiva: atención → información (yo elijo qué consumir). Perspectiva de la economía de la atención: sistemas de información → atención (las plataformas compiten para capturarla y retenerla). Ninguno de los dos está mal.
Describen diferentes niveles. Ahora a tu pregunta final: > entonces, ¿existe realmente una gran cantidad de información o sólo una economía en torno a la información?
Los separaría. La "riqueza de información" es real. La humanidad realmente tiene un acceso sin precedentes al conocimiento: los artículos científicos. archivos históricos.
Tutoriales. mapas. idiomas. películas. conferencias. registros públicos. Esa abundancia existe independientemente de los modelos de negocio.
Pero las plataformas modernas envuelven esa abundancia dentro de una 'economía de la atención'.
Así que la frase "economía de la información" puede desdibujar dos cosas distintas: 1. Información como abundancia de conocimiento 2. Información como competencia de atención gestionada económicamente.
El primero es un tesoro de civilización. El segundo es una estructura de mercado. Y su malestar proviene de notar que las personas a menudo hablan como si fueran la misma cosa. No lo son.
Tanto una biblioteca como un feed de desplazamiento infinito contienen información, pero uno dice principalmente "aquí si me necesitas" mientras que el otro dice "antes de irte, ¿quizás veintisiete miniaturas cargadas de emociones?".`;

var esSND=['attentionES.mp3',[0.000000,25.859125],[25.966861,45.551463],[45.600341,58.381474],[58.478215,70.397331],[70.441267,82.703416],[82.756174,91.534985],[91.622907,108.177644],[108.230438,122.357435],[122.445359,130.837083],[130.889867,141.727007],[141.797356,155.027057],[155.097455,171.054022],[171.054022,177.932789],[177.967996,187.608785],[187.679180,203.600654],[203.653374,221.035056],[221.175727,231.537899],[231.590619,242.533316],[242.638850,254.883403],[254.953757,273.302939],[273.461303,284.896567],[284.931759,297.704037],[297.739262,310.652277],[310.687507,317.707022],[317.794967,331.393043],[331.869146,345.859781],[345.859781,360.303387]];
storyline.snd.es = {};storyline.snd.es.p = storyline.sndURL+esSND[0];esSND.splice(0,1);storyline.snd.es.t = esSND;